### ISSUE TITLE
[Tomcat7]Leak error and Tomcat is never shutdown

### ISSUE THREAD

**Issue by takezoe** [play2war/play2-war-plugin#108]
When I execute CATALINA_HOME/bin/shutdown.sh, I got the following error and Tomcat is never shutdown.

```
2012/11/28 3:24:43 org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
FATAL: The web application [] created a ThreadLocal with key of type [scala.concurrent.stm.ccstm.InTxnImpl$] (value [scala.concurrent.stm.ccstm.InTxnImpl$@37c9313b]) and a value of type [scala.concurrent.stm.ccstm.InTxnImpl] (value [InTxnImpl@4bb2668f(Detached, slot=-1695, subsumptionAllowed=true, priority=-706448867, readCount=0, bargeCount=0, writeCount=0, readVersion=0x16b9, cumulativeBlockingNanos=0, commitBarrier=null)]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

My environment :
- Tomcat 7.0.29
- Play 2.0.4
- play2-war-plugin 0.8.1 (Servlet 2.5 mode)

Are there anyone who got the same problem?

**Comment by dlecan** [comment]
Yes, for memory leaks see #29, and [Akka#2672](https://www.assembla.com/spaces/akka/tickets/2672) and [Akka#2479](https://www.assembla.com/spaces/akka/tickets/2479).

But Tomcat shutdown has always been successful.

When Tomcat hangs, can you do a thread dump ?

**Comment by takezoe** [comment]
This is a part of thread dump. It seems that Akka threads are remained.

```
"promise-akka.actor.default-dispatcher-8" prio=10 tid=0x00007f041001c000 nid=0x205b waiting on condition [0x00007f03fd606000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000ff725390> (a akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinPool)
        at akka.jsr166y.ForkJoinPool.scan(ForkJoinPool.java:1594)
        at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1479)
        at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

"ajp-bio-8009-exec-4" daemon prio=10 tid=0x00007f0428763800 nid=0x2053 runnable [0x00007f03fde0e000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:146)
        at org.apache.coyote.ajp.AjpProcessor.read(AjpProcessor.java:309)
        at org.apache.coyote.ajp.AjpProcessor.readMessage(AjpProcessor.java:364)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:128)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
        - locked <0x00000000ffa0cda8> (a org.apache.tomcat.util.net.SocketWrapper)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
```

I tried Play 2.0.1 with play2-war-plugin 0.8.1, Tomcat shutdown was successful.

**Comment by dlecan** [comment]
Hum, this is a Play and its embed dependencies issue.

A quick look at diff between Play 2.0.1 and 2.0.4 Build.scala file gives that (extract):

```
...

-            "org.scala-tools"                   %%   "scala-stm"                %   "0.4",
+            "org.scala-tools"                   %%   "scala-stm"                %   "0.5",

...

-            "com.typesafe.akka"                 %    "akka-actor"               %   "2.0.1",
+            "com.typesafe.akka"                 %    "akka-actor"               %   "2.0.2",
```

Scala STM has been upgraded, and your initial bug report shows `scala.concurrent.stm.ccstm.InTxnImpl$` statements ...

Can you downgrade Scala STM to 0.4 ?

**Comment by takezoe** [comment]
Thanks, I downgraded Scala STM to 0.4, however Tomcat is not still terminated.

Of course, this is not an issue of play2-war-plugin. I expect this trouble is caused by changes of Play or Akka. But this is a serious problem when running Play2 application on Tomcat using play2-war-plugin. I'll continue to investigate more details and report that result.

**Comment by dlecan** [comment]
Can you post the full thread dump ?

**Comment by dlecan** [comment]
I think this a Play2 issue.
Please reopen if you think it's a Play2War issue instead.
