### ISSUE TITLE
New application.context feature should work with Play2War

### ISSUE THREAD

**Issue by dlecan** [play2war/play2-war-plugin#116]
Need to update:
- integration tests
- sample configuration

**Comment by dlecan** [comment]
This doesn't work yet:

```
2012-12-05 18:36:16,754 - [DEBUG] - from play in http-apr-8080-exec-3 
Async timeout for HTTP requests: -1 seconds

2012-12-05 18:36:16,851 - [TRACE] - from play in http-apr-8080-exec-3 
HTTP request content: GET /p2wsample/
URI: /p2wsample/
Method: GET
Path: /p2wsample/
Parameters: Map()
Headers: Map(ACCEPT -> Buffer(*/*), ACCEPT-ENCODING -> Buffer(gzip, deflate), ACCEPT-LANGUAGE -> Buffer(en-us), CONNECTION -> Buffer(Keep-Alive), HOST -> Buffer(localhost:8080), USER-AGENT -> Buffer(Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)))
Cookies: Map()

2012-12-05 18:36:16,878 - [ERROR] - from application in http-apr-8080-exec-3 


! @6chb5i40l - Internal server error, for (GET) [/p2wsample/] ->

play.api.Configuration$$anon$1: Configuration error[Invalid application context]
    at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:74) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.api.Configuration.reportError(Configuration.scala:552) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.api.Application$$anonfun$routes$3$$anonfun$apply$13.apply(Application.scala:235) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.api.Application$$anonfun$routes$3$$anonfun$apply$13.apply(Application.scala:233) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at scala.Option.map(Option.scala:145) ~[org.scala-lang.scala-library-2.10.0-RC1.jar:na]
    at play.api.Application$$anonfun$routes$3.apply(Application.scala:233) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.api.Application$$anonfun$routes$3.apply(Application.scala:232) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at scala.Option.map(Option.scala:145) ~[org.scala-lang.scala-library-2.10.0-RC1.jar:na]
    at play.api.Application$class.routes(Application.scala:232) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.api.DefaultApplication.routes$lzycompute(Application.scala:373) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.api.DefaultApplication.routes(Application.scala:373) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.api.GlobalSettings$$anonfun$onRouteRequest$1.apply(GlobalSettings.scala:83) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.api.GlobalSettings$$anonfun$onRouteRequest$1.apply(GlobalSettings.scala:83) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at scala.Option.flatMap(Option.scala:170) ~[org.scala-lang.scala-library-2.10.0-RC1.jar:na]
    at play.api.GlobalSettings$class.onRouteRequest(GlobalSettings.scala:83) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.api.DefaultGlobal$.onRouteRequest(GlobalSettings.scala:160) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:54) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:53) ~[play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at scala.util.Either$RightProjection.map(Either.scala:536) [org.scala-lang.scala-library-2.10.0-RC1.jar:na]
    at play.core.server.Server$class.sendHandler$1(Server.scala:53) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:83) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:82) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at scala.util.Either$RightProjection.flatMap(Either.scala:523) [org.scala-lang.scala-library-2.10.0-RC1.jar:na]
    at play.core.server.Server$class.getHandlerFor(Server.scala:82) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
    at play.core.server.servlet.Play2WarServer.getHandlerFor(Play2Server.scala:59) [com.github.play2war.play2-war-core-common_2.10-0.9-SNAPSHOT.jar:0.9-SNAPSHOT]
    at play.core.server.servlet.Play2GenericServletRequestHandler.apply(RequestHandler.scala:280) [com.github.play2war.play2-war-core-common_2.10-0.9-SNAPSHOT.jar:0.9-SNAPSHOT]
    at play.core.server.servlet.Play2WarServer$.handleRequest(Play2Server.scala:54) [com.github.play2war.play2-war-core-common_2.10-0.9-SNAPSHOT.jar:0.9-SNAPSHOT]
    at play.core.server.servlet.GenericPlay2Servlet.service(Play2CommonServlet.scala:78) [com.github.play2war.play2-war-core-common_2.10-0.9-SNAPSHOT.jar:0.9-SNAPSHOT]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.32]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.32]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.32]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.32]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) [catalina.jar:7.0.32]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.32]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929) [catalina.jar:7.0.32]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.32]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.32]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002) [tomcat-coyote.jar:7.0.32]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585) [tomcat-coyote.jar:7.0.32]
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1813) [tomcat-coyote.jar:7.0.32]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_35]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_35]
    at java.lang.Thread.run(Thread.java:662) [na:1.6.0_35]

2012-12-05 18:36:17,028 - [ERROR] - from play in http-apr-8080-exec-3 
Oops, unexpected message received in Play server (please report this problem): Left(SimpleResult(500, Map(Content-Type -> text/html; charset=utf-8)))

2012-12-05 18:36:17,032 - [TRACE] - from play in http-apr-8080-exec-3 
Sending simple result: SimpleResult(500, Map())

2012-12-05 18:36:17,036 - [TRACE] - from play in http-apr-8080-exec-3 
Result without Content-length
```

**Comment by dlecan** [comment]
Much better after fixing exception (-80 test errors).
But there are still some failures.
