### ISSUE TITLE
Jboss 7.1.1 + play 2.1-RC does not deploy

### ISSUE THREAD

**Issue by tm4rini** [play2war/play2-war-plugin#117]
I have a project that uses play2.1-RC with Ebean which I want to deploy in jboss 7.1.1, I disable default page welcome in "standalone / configuration / standalone.xml" changed enable-welcome-root = "true "to enable-welcome-root =" false ". Also rename the WAR file generated for ROOT.war before deploying.

The following error is generated:

```
11:11:57,983 ERROR [org.reflections.Reflections] (MSC service thread 1-1) could not create Vfs.Dir from url. ignoring the exception and continuing: org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [vfs:/C:/Users/Thiago/Desktop/content/ROOT.war/WEB-INF/lib/play.play_2.10-2.1-RC1.jar/]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:108) [org.reflections.reflections-0.9.8.jar:]
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:90) [org.reflections.reflections-0.9.8.jar:]
        at org.reflections.Reflections.scan(Reflections.java:165) [org.reflections.reflections-0.9.8.jar:]
        at org.reflections.Reflections.<init>(Reflections.java:94) [org.reflections.reflections-0.9.8.jar:]
        at play.libs.Classpath.getReflections(Classpath.java:48) [play.play-java_2.10-2.1-RC1.jar:2.1-RC1]
        at play.libs.Classpath.getTypes(Classpath.java:25) [play.play-java_2.10-2.1-RC1.jar:2.1-RC1]
        at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:62) [play.play-java-ebean_2.10-2.1-RC1.jar:2.1-RC1]
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:62) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:62) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at scala.collection.immutable.List.foreach(List.scala:309) [org.scala-lang.scala-library-2.10.0-RC1.jar:]
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:62) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at play.api.Play$$anonfun$start$1.apply(Play.scala:62) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at play.api.Play$$anonfun$start$1.apply(Play.scala:62) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at play.api.Play$.start(Play.scala:61) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at play.core.server.servlet.WarApplication.<init>(Play2Server.scala:103) [com.github.play2war.play2-war-core-common_2.10-0.9-RC1.jar:0.9-RC1]
        at play.core.server.servlet.Play2WarServer$.<init>(Play2Server.scala:34) [com.github.play2war.play2-war-core-common_2.10-0.9-RC1.jar:0.9-RC1]
        at play.core.server.servlet.Play2WarServer$.<clinit>(Play2Server.scala) [com.github.play2war.play2-war-core-common_2.10-0.9-RC1.jar:0.9-RC1]
        at play.core.server.servlet.GenericPlay2Servlet.contextInitialized(Play2CommonServlet.scala:87) [com.github.play2war.play2-war-core-common_2.10-0.9-RC1.jar:0.9-RC1]
        at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3392) [jbossweb-7.0.13.Final.jar:]
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:3850) [jbossweb-7.0.13.Final.jar:]
        at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [rt.jar:1.6.0_29]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [rt.jar:1.6.0_29]
        at java.lang.Thread.run(Thread.java:662) [rt.jar:1.6.0_29]

11:11:58,039 ERROR [org.reflections.Reflections] (MSC service thread 1-1) could not create Vfs.Dir from url. ignoring the exception and continuing: org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [vfs:/C:/Users/Thiago/Desktop/content/ROOT.war/WEB-INF/lib/p2war21_2.10-1.0-SNAPSHOT.jar/]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:108) [org.reflections.reflections-0.9.8.jar:]
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:90) [org.reflections.reflections-0.9.8.jar:]
        at org.reflections.Reflections.scan(Reflections.java:165) [org.reflections.reflections-0.9.8.jar:]
        at org.reflections.Reflections.<init>(Reflections.java:94) [org.reflections.reflections-0.9.8.jar:]
        at play.libs.Classpath.getReflections(Classpath.java:48) [play.play-java_2.10-2.1-RC1.jar:2.1-RC1]
        at play.libs.Classpath.getTypes(Classpath.java:25) [play.play-java_2.10-2.1-RC1.jar:2.1-RC1]
        at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:62) [play.play-java-ebean_2.10-2.1-RC1.jar:2.1-RC1]
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:62) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:62) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at scala.collection.immutable.List.foreach(List.scala:309) [org.scala-lang.scala-library-2.10.0-RC1.jar:]
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:62) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at play.api.Play$$anonfun$start$1.apply(Play.scala:62) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at play.api.Play$$anonfun$start$1.apply(Play.scala:62) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at play.api.Play$.start(Play.scala:61) [play.play_2.10-2.1-RC1.jar:2.1-RC1]
        at play.core.server.servlet.WarApplication.<init>(Play2Server.scala:103) [com.github.play2war.play2-war-core-common_2.10-0.9-RC1.jar:0.9-RC1]
        at play.core.server.servlet.Play2WarServer$.<init>(Play2Server.scala:34) [com.github.play2war.play2-war-core-common_2.10-0.9-RC1.jar:0.9-RC1]
        at play.core.server.servlet.Play2WarServer$.<clinit>(Play2Server.scala) [com.github.play2war.play2-war-core-common_2.10-0.9-RC1.jar:0.9-RC1]
        at play.core.server.servlet.GenericPlay2Servlet.contextInitialized(Play2CommonServlet.scala:87) [com.github.play2war.play2-war-core-common_2.10-0.9-RC1.jar:0.9-RC1]
        at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3392) [jbossweb-7.0.13.Final.jar:]
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:3850) [jbossweb-7.0.13.Final.jar:]
        at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [rt.jar:1.6.0_29]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [rt.jar:1.6.0_29]
        at java.lang.Thread.run(Thread.java:662) [rt.jar:1.6.0_29]
```

With that tried the alternative of adding the dependence on Build.scala

"com.dlecan.reflections"% "jboss7-vfs-integration"% "1.0.1"

but the same error still persists.

**Comment by dlecan** [comment]
README.md is not clear, but "jboss7-vfs-integration" in mandatory for all JBoss 7.x series.
I will refactor this part of the documentation to be clearer.

Your exception appears when VFS is not correctly initialized, but this should be done by the extention "jboss7-vfs-integration" ...

I will publish a 1.0.2 version which will output some logs, in order to be sure this initialization:
- is done
- is done before Play server loading

I'll tell you when to update.

**Comment by tm4rini** [comment]
thanks for the reply.

**Comment by dlecan** [comment]
Can you update "com.dlecan.reflections"% "jboss7-vfs-integration"% "1.0.1" to 1.0.2 ?

You should see such logs at startup:

```
... JBoss VFS initialisation for Play applications...
... JBoss VFS initialisation for Play applications done.
... PlayServletWrapper > contextInitialized
```

**Comment by dlecan** [comment]
FYI, my play 2.1 ebean sample works as expected on JBoss 7.1.
If I remove jboss7-vfs-integration jar, I get **the same** exception as you.

Something must be wrong with jboss7-vfs-integration loading.

What's the 1st letter of your project's name ?

**Comment by tm4rini** [comment]
I tried with 2 project

with the first "M" and the other with "P"

**Comment by dlecan** [comment]
Did you see this [comment](https://github.com/dlecan/play2-war-plugin/issues/117#issuecomment-11574592)?

**Comment by thesurlydev** [comment]
I'm having this same issue as well. Running Play 2.0.4 with JBoss 7.1.1. Plugin version is 0.8.1. I do not see "JBoss VFS initialisation for Play applications" in the log.

**Comment by dlecan** [comment]
@digitalsanctum Which version of `jboss7-vfs-integration` lib ?

**Comment by thesurlydev** [comment]
1.0.2

**Comment by dlecan** [comment]
@digitalsanctum Thx. What is the 1st letter of your project's name ?

**Comment by thesurlydev** [comment]
first letter is P

**Comment by dlecan** [comment]
Hi guys,

I have totally rewritten org.reflection JBoss 7 integration into Play2.
It is now loaded as a Play2 plugin, which should ensure its loading before ebean plugin.

If you want to try it, follow theses intructions:
- Remove old `jboss7-vfs-integration` dependency (servlet-base loading)
- Add this dependency: `"com.github.play2war.ext" %% "jboss7-reflections-vfs-integration-play2" % "1.0.0"`

Optional, but recommended:
- Add this dependency: `"com.github.play2war.ext" %% "redirect-playlogger" % "1.0.1"`

See [this comment](https://github.com/dlecan/play2-war-plugin/issues/101#issuecomment-11704585) for explanations.

**Comment by dlecan** [comment]
Any news guys ?

**Comment by dlecan** [comment]
@digitalsanctum  @guetomarini Please, do not hesitate to reopen this issue if you have more information to provide.
