### ISSUE TITLE
Memory leak with Tomcat, Guice and Play 2.1-RC2

### ISSUE THREAD

**Issue by antoineleclair** [play2war/play2-war-plugin#124]
I'm using play2-war (dev branch, 2cd7c78dfcae1b81cc7fe76b5cf71dcfa7cda10f) and Tomcat 7. My app uses Guice for dependency injection in the controllers. I eventually get a PermGen space OutOfMemory. Maybe it has something to do with the fact that I see Catalina class loader in the stack trace? (`org.apache.catalina.loader.WebappClassLoader.loadClass`)

Here's the stacktrace that I get:

```
ERROR 2013-01-16 11:07:55,477 - Waiting for a promise, but got an error: java.lang.OutOfMemoryError: PermGen space
java.lang.RuntimeException: java.lang.OutOfMemoryError: PermGen space
    at helpers.Security$AuthenticatedAction.call(Security.java:49) ~[gpb_2.10-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at play.db.jpa.TransactionalAction$1.apply(TransactionalAction.java:19) ~[play.play-java-jpa_2.10-2.1-RC2.jar:2.1-RC2]
    at play.db.jpa.TransactionalAction$1.apply(TransactionalAction.java:17) ~[play.play-java-jpa_2.10-2.1-RC2.jar:2.1-RC2]
    at play.db.jpa.JPA.withTransaction(JPA.java:101) ~[play.play-java-jpa_2.10-2.1-RC2.jar:2.1-RC2]
    at play.db.jpa.TransactionalAction.call(TransactionalAction.java:14) ~[play.play-java-jpa_2.10-2.1-RC2.jar:2.1-RC2]
    at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:74) ~[play.play_2.10-2.1-RC2.jar:2.1-RC2]
    at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:73) ~[play.play_2.10-2.1-RC2.jar:2.1-RC2]
    at play.libs.F$Promise$PromiseActor.onReceive(F.java:396) ~[play.play_2.10-2.1-RC2.jar:2.1-RC2]
    at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) ~[com.typesafe.akka.akka-actor_2.10-2.1.0.jar:na]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) ~[com.typesafe.akka.akka-actor_2.10-2.1.0.jar:na]
    at akka.actor.ActorCell.invoke(ActorCell.scala:386) ~[com.typesafe.akka.akka-actor_2.10-2.1.0.jar:na]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) ~[com.typesafe.akka.akka-actor_2.10-2.1.0.jar:na]
    at akka.dispatch.Mailbox.run(Mailbox.scala:212) ~[com.typesafe.akka.akka-actor_2.10-2.1.0.jar:na]
    at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:502) ~[com.typesafe.akka.akka-actor_2.10-2.1.0.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) ~[org.scala-lang.scala-library-2.10.0.jar:na]
java.lang.OutOfMemoryError: PermGen space
    at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.6.0_21]
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632) ~[na:1.6.0_21]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:616) ~[na:1.6.0_21]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[na:1.6.0_21]
    at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2889) ~[catalina.jar:7.0.27]
    at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1170) ~[catalina.jar:7.0.27]
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1678) ~[catalina.jar:7.0.27]
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1556) ~[catalina.jar:7.0.27]
    at controllers.admin.ContestAmounts.<clinit>(ContestAmounts.java:34) ~[gpb_2.10-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at controllers.admin.ContestAmounts$$FastClassByGuice$$8a8713d.newInstance(<generated>) ~[com.google.inject.guice-3.0.jar:1.0-SNAPSHOT]
    at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) ~[com.google.inject.guice-3.0.jar:na]
    at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60) ~[com.google.inject.guice-3.0.jar:na]
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[com.google.inject.guice-3.0.jar:na]
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254) ~[com.google.inject.guice-3.0.jar:na]
    at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978) ~[com.google.inject.guice-3.0.jar:na]
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024) ~[com.google.inject.guice-3.0.jar:na]
    at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974) ~[com.google.inject.guice-3.0.jar:na]
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013) ~[com.google.inject.guice-3.0.jar:na]
    at helpers.DependencyHelper.getInjectedInstance(DependencyHelper.java:20) ~[gpb_2.10-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at Global.getControllerInstance(Global.java:32) ~[gpb_2.10-1.0-SNAPSHOT.jar:na]
    at play.core.j.JavaGlobalSettingsAdapter.getControllerInstance(JavaGlobalSettingsAdapter.scala:45) ~[play.play_2.10-2.1-RC2.jar:2.1-RC2]
    at Routes$$anonfun$routes$1$$anonfun$applyOrElse$77$$anonfun$apply$227.apply(routes_routing.scala:1153) ~[gpb_2.10-1.0-SNAPSHOT.jar:na]
    at Routes$$anonfun$routes$1$$anonfun$applyOrElse$77$$anonfun$apply$227.apply(routes_routing.scala:1153) ~[gpb_2.10-1.0-SNAPSHOT.jar:na]
    at play.core.Router$HandlerInvoker$$anon$6$$anon$1.invocation(Router.scala:141) ~[play.play_2.10-2.1-RC2.jar:2.1-RC2]
    at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:31) ~[play.play_2.10-2.1-RC2.jar:2.1-RC2]
    at play.GlobalSettings$1.call(GlobalSettings.java:63) ~[play.play_2.10-2.1-RC2.jar:2.1-RC2]
    at helpers.Security$AuthenticatedAction.setUsernameAndCall(Security.java:56) ~[gpb_2.10-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at helpers.Security$AuthenticatedAction.call(Security.java:44) ~[gpb_2.10-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at play.db.jpa.TransactionalAction$1.apply(TransactionalAction.java:19) ~[play.play-java-jpa_2.10-2.1-RC2.jar:2.1-RC2]
    at play.db.jpa.TransactionalAction$1.apply(TransactionalAction.java:17) ~[play.play-java-jpa_2.10-2.1-RC2.jar:2.1-RC2]
    at play.db.jpa.JPA.withTransaction(JPA.java:101) ~[play.play-java-jpa_2.10-2.1-RC2.jar:2.1-RC2]
    at play.db.jpa.TransactionalAction.call(TransactionalAction.java:14) ~[play.play-java-jpa_2.10-2.1-RC2.jar:2.1-RC2]
```

**Comment by dlecan** [comment]
What did you do to get that ? Hot redeployment in Tomcat ?
Or just using application and then getting this exception after a while ?

Profilling is necessary to understand what happens. I don't know what I can do here (or what Play2war can do also).
Guava (Guice dependency) has many memory leaks, which can lead to OOME on Tomcat after redeployment.

Eg.: http://code.google.com/p/google-guice/issues/detail?id=630#c8

You can try to increase permgen space at startup.

**Comment by antoineleclair** [comment]
I got that after a while. Also, when we deploy we restart Tomcat.

**Comment by dlecan** [comment]
Maybe something should be done by Play2War when servlet context is destroyed.
Any idea ?

**Comment by antoineleclair** [comment]
Not sure of what I'm saying, but could it be caused by the fact that Play 2.1 has changed the way it loads classes? If they are created by `org.apache.catalina.loader.WebappClassLoader` instead of Play, could it cause a leak?

**Comment by dlecan** [comment]
Do you mean this wasn't an issue with Play 2.0.x ?

**Comment by antoineleclair** [comment]
I don't think it was an issue before. But in Play 2.0.x, I was using the [injection plugin](https://github.com/typesafehub/play-plugins/tree/master/inject), which is not supported by Play2.1. I now use Guice, as shown in the [example](https://github.com/playframework/Play20/blob/master/documentation/manual/javaGuide/main/inject/JavaInjection.md).

**Comment by dlecan** [comment]
Any news on this issue ?

**Comment by antoineleclair** [comment]
We stopped using Tomcat because of this bug. Also, we are now starting play with `-XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC`, which might have helped when using Tomcat (never tested).

**Comment by dlecan** [comment]
Thanks

**Comment by sdpatil** [comment]
I am using Play framework 2.2 and plugin version 1.2 and deploying my application in apache tomcat 7.0.53.

I am facing same problem. I tried profiling the application and it seems that when i stop the application and undeploy it leaves 3 threads running one is play-scheduler-1, play-internal-execution-context-1 and  play-akka.actor.default-dispatcher-1. Because of these 3 threads tomcat is com

![screen shot 2014-12-23 at 9 33 14 pm](https://cloud.githubusercontent.com/assets/2074730/5546028/045e0c3e-8aec-11e4-9fdd-d804e9a00086.png)

Because of this the permgen keeps increasing and after 2-3 redeploys without server restart crashes server. I was wondering if there is a way to release/shutdown these thread pools. I see these warnings when i try to stop the application

![screen shot 2014-12-23 at 9 34 52 pm](https://cloud.githubusercontent.com/assets/2074730/5546039/544c5aca-8aec-11e4-8416-5ea642e28628.png)
