### ISSUE TITLE
"org.apache.catalina.connector.Request.startAsync" not supported ?

### ISSUE THREAD

**Issue by gguan** [play2war/play2-war-plugin#125]
When I deploy war package on company's specific tomcat version. I get following errors.

```
java.lang.IllegalStateException: Not supported.
    at org.apache.catalina.connector.Request.startAsync(Request.java:1673)
    at org.apache.catalina.connector.Request.startAsync(Request.java:1666)
    at org.apache.catalina.connector.RequestFacade.startAsync(RequestFacade.java:1023)
    at javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:364)
    at javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:364)
    at play.core.server.servlet30.Play2Servlet30RequestHandler.<init>(RequestHandler30.scala:21)
    at play.core.server.servlet30.Play2Servlet.getRequestHandler(Play2Servlet30.scala:21)
    at play.core.server.servlet30.Play2Servlet.getRequestHandler(Play2Servlet30.scala:18)
    at play.core.server.servlet.GenericPlay2Servlet.service(Play2CommonServlet.scala:76)
```

I looks like asynchronous feature is not configured. I'm quite new to tomcat. Can you point me how to config this in play's project?

**Comment by dlecan** [comment]
You doesn't say anything about your company's specific Tomcat version.
On standard Tomcat version, Async request are "on" by default, so something provided by your disables it.

Maybe you have a Valve or a Filter which disable async request ...

**Comment by gguan** [comment]
I'm not sure why company's tomcat turns off Async by default. But I googled the problem and find some people has similar issue when using tomcat Async. It is solved by adding:
servletRequest.setAttribute("org.apache.catalina.ASYNC_SUPPORTED", true)
in servlet methods. I add this line in Play2-war-plugin Play2Servlet30RequestHandler class, and compile in my local box. Then the war package generated by war-plugin worked.

**Comment by dlecan** [comment]
You can understand I can't add this code in Play2War it is to linked with Tomcat.
Can you set it through a servlet filter ?
