### ISSUE TITLE
[Play 2.1] Remote deployments on Tomcat 7 fail

### ISSUE THREAD

**Issue by momomagic** [play2war/play2-war-plugin#132]
I got this exception when I try to deploy the war file 

```
INFO: Illegal access: this web application instance has been stopped already.  Could not load com.mysql.jdbc.DatabaseMetaData$9.  The eventual following stack trace is caused by an error thrown for debugging purposes as well $
java.lang.IllegalStateException
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1597)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1556)
        at com.mysql.jdbc.DatabaseMetaData.getTables(DatabaseMetaData.java:4997)
        at com.jolbox.bonecp.BoneCP.isConnectionHandleAlive(BoneCP.java:677)
        at com.jolbox.bonecp.ConnectionTesterThread.run(ConnectionTesterThread.java:103)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
```

**Comment by dlecan** [comment]
Is it a redeployment ?
Play container isn't properly unload when container is stopped. After that, next deployment is a real mess ...

**Comment by momomagic** [comment]
when I deploy it to my local machine I got this error until I restart the tomcat it self ,  but If I deploy it to remote server it always crash with that exception

**Comment by dlecan** [comment]
> when I deploy it to my local machine I got this error until I restart the tomcat it self

Ok, redeployment doesn't work because Play doesn't stop properly.

>  If I deploy it to remote server it always crash with that exception 

Interesting. How do you deploy remotely on Tomcat ?

**Comment by dlecan** [comment]
Any news on this issue ?

**Comment by dlecan** [comment]
Please, do not hesitate to reopen this issue if you have more information to provide.

**Comment by mmalfertheiner** [comment]
I have the same problem. Where you able to solve it?

**Comment by dlecan** [comment]
@mmalfertheiner no, the reporter didn't give enough informations.
If you have a similar issue, the best is to open a new one.
Thank you
