### ISSUE TITLE
ClassCastException on Tomcat 7

### ISSUE THREAD

**Issue by dragojeremic** [play2war/play2-war-plugin#143]
Hi guys,

I'm tying to deploy war on my local tomcat7, but I'm  getting an error:

```
org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [Play] in context with path [/] threw exception [Servlet execution threw an exception] with root cause
java.lang.ClassCastException: interface akka.actor.ActorRefProvider is not assignable from class akka.actor.LocalActorRefProvider
    at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:70)
    at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:67)
    at scala.util.Try$.apply(Try.scala:161)
    at akka.actor.ReflectiveDynamicAccess.getClassFor(DynamicAccess.scala:67)
    at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:85)
    at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:546)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:111)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:104)
    at play.core.Invoker$.<init>(Invoker.scala:21)
    at play.core.Invoker$.<clinit>(Invoker.scala)
    at play.api.libs.concurrent.Execution$Implicits$.defaultContext$lzycompute(Execution.scala:8)
    at play.api.libs.concurrent.Execution$Implicits$.defaultContext(Execution.scala:7)
    at play.api.libs.concurrent.Execution$.<init>(Execution.scala:11)
    at play.api.libs.concurrent.Execution$.<clinit>(Execution.scala)
    at play.core.server.servlet.Play2GenericServletRequestHandler.handleAction$1(RequestHandler.scala:380)
    at play.core.server.servlet.Play2GenericServletRequestHandler.apply(RequestHandler.scala:368)
    at play.core.server.servlet.Play2WarServer$.handleRequest(Play2Server.scala:49)
    at play.core.server.servlet.GenericPlay2Servlet.service(Play2CommonServlet.scala:78)
```

Can you give me any hint how to fix it?
Thanks

**Comment by dlecan** [comment]
Please, give more informations:
- Play2war version
- Play version
- Exact version of Tomcat 7
- JVM model and version

Thank you

**Comment by dragojeremic** [comment]
Ah sorry,

Play2war version: 0.9
Play version: 2.1.0 
Tomcat 7.0.16
Windows7 OS
jdk1.6.0_21
jre1.6.0_21

Application is done in Java mode...

**Comment by dlecan** [comment]
Can you provide a test case, or at least show the way you have coded your Java action ?

**Comment by dragojeremic** [comment]
It is happening for every action, for example:

public class User extends Controller {

```
public static Form<Login> loginForm = Form.form(Login.class);

public static Result login() {
    return ok(
        login.render(loginForm)
    );
}
```

}

**Comment by dlecan** [comment]
Was that ok with Play2War 0.9-RC2 or 0.9-RC1 ?

**Comment by dlecan** [comment]
I tried to reproduce your issue with the Play 2.1 provided sample : `samples/java/helloworld`.
Unfortunately, despite:
- Tomcat 7.0.16
- JDK 1.6.0_29
- WinXP
- Play 2.1.0
- Play2War 0.9

I was not able to reproduce your issue.

I know that JDK and OS are not the same as yours, but I don't think it matters.

What about extra dependencies or plugins in your project ?

**Comment by dragojeremic** [comment]
None...

It's probably some java dependency in my app,
I'll see what I can do.

Thanks for you're effort, I appreciate it.

**Comment by dlecan** [comment]
Any news ?
Please reopen this issue if you have more information to provide.
