### ISSUE TITLE
[Jboss 7.1.1] Conflict between Netty's librairies (Play <-> Jboss)

### ISSUE THREAD

**Issue by matmsh** [play2war/play2-war-plugin#164]
I used play2war 0.9  to create anormdemo1.war and playScalaDemo.war, each with an application context. When I deployed them in Jboss 7.1.1 standalone, I get the following error. 

```
14:54:26,837 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-15) JBAS015876: Starting deployment of "playScalaDemo.war"
14:54:26,837 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-16) JBAS015876: Starting deployment of "anormdemo1.war"
14:54:29,288 INFO  [org.jboss.as.pojo] (MSC service thread 1-1) JBAS017000: Found legacy bean/pojo namespace: urn:jboss:bean-deployer:2.0 - might be missing some xml features (potential exceptions).
14:54:29,496 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/playScalaDemo]] (MSC service thread 1-14) PlayServletWrapper > contextInitialized
14:54:29,516 INFO  [org.jboss.as.pojo] (MSC service thread 1-3) JBAS017000: Found legacy bean/pojo namespace: urn:jboss:bean-deployer:2.0 - might be missing some xml features (potential exceptions).
14:54:29,571 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-15) MSC00001: Failed to start service jboss.deployment.unit."anormdemo1.war".INSTALL: org.jboss.msc.service.StartException in service jboss.deployment.unit."anormdemo1.war".INSTALL: Failed to process phase INSTALL of deployment "anormdemo1.war"
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:119) [jboss-as-server-7.1.1.Final.jar:7.1.1.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [rt.jar:1.6.0_21]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [rt.jar:1.6.0_21]
        at java.lang.Thread.run(Thread.java:619) [rt.jar:1.6.0_21]
Caused by: org.jboss.msc.service.DuplicateServiceException: Service jboss.pojo."org.jboss.netty.internal.LoggerConfigurator".DESCRIBED is already registered
        at org.jboss.msc.service.ServiceRegistrationImpl.setInstance(ServiceRegistrationImpl.java:154) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at org.jboss.msc.service.ServiceControllerImpl.startInstallation(ServiceControllerImpl.java:227) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at org.jboss.msc.service.ServiceContainerImpl.install(ServiceContainerImpl.java:560) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:201) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2228) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:201) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2228) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at org.jboss.msc.service.ServiceBuilderImpl.install(ServiceBuilderImpl.java:307) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at org.jboss.as.pojo.ParsedKernelDeploymentProcessor.describeBean(ParsedKernelDeploymentProcessor.java:94)
        at org.jboss.as.pojo.ParsedKernelDeploymentProcessor.deploy(ParsedKernelDeploymentProcessor.java:76)
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:113) [jboss-as-server-7.1.1.Final.jar:7.1.1.Final]
        ... 5 more
```

The above problem is mentioned in :
https://issues.jboss.org/browse/IMMUTANT-144

I followed the suggestion in the the above link and removed pojo subsystem from 
my standalone.xml.  When start Jboss again,  I no longet get the error : 

```
"org.jboss.netty.internal.LoggerConfigurator".DESCRIBED is already registered
```

But I still get anormdemo1.war.failed and playScalaDemo.war.failed, and there is no error in the log. 

I get HTTP error 404, as expected,  when I try 
 http://localhost:8080/anormdemo1/
or http://localhost:8080/playScalaDemo/

Note that, if I only deploy  one of normdemo1.war, playScalaDemo.war in Jboss,
it works. 

Thanks in advance for your assistance!
Shing

**Comment by matmsh** [comment]
I have found a solution. 

In addition to removing pojo subsystem in  Jboss standalone.xml,    in each of my Play application, I added 
META-INF/jboss-beans.xml:

```
<bean name="org.jboss.netty.internal.LoggerConfigurator"
       class="org.jboss.netty.container.microcontainer.NettyLoggerConfigurator" />
```

so that the bean name is unique amongst my Play apps. 

Please see http://lists.jboss.org/pipermail/netty-users/2011-June/004541.html

**Comment by dlecan** [comment]
Strange, you are the first one who has issues between Netty's librairies of Play and JBoss ones.

Thank you for the solution.

**Comment by adelarsq** [comment]
I found another solution. Just need to exclude org.jboss.netty from build (file Build.scala):

```
val appDependencies = Seq(
      ...
      "org.jboss.as" % "jboss-as-jms-client-bom" % "7.1.0.Final" exclude("org.jboss.netty", "netty")
)
```

May be usefull for someone else.
