### ISSUE TITLE
Websphere 8.5.5 - models.Customer is NOT an Entity Bean registered with this server

### ISSUE THREAD

**Issue by KevinSheedy** [play2war/play2-war-plugin#167]
The app works fine when I run it using `play ~run`
When I try deploying it as a war on Websphere 8.5.5, I get the error message:

```
models.MyModel is NOT an Entity Bean registered with this server
```

I tried reading the [ebean docs](http://www.avaje.org/static/javadoc/pub/com/avaje/ebean/config/ServerConfig.html#addJar(java.lang.String) regarding where ebean searches for model classes. Based on these, I created the file `APP_HOME\conf\ebean.properties` and set the value:

```
ebean.search.jars=myplayapp.jar
```

Afraid I still get the same error.

**Comment by dlecan** [comment]
Classloading issue ? Parent_last vs parent_first ?

**Comment by nickcousyn** [comment]
Facing the same issue on Websphere 8.5 Liberty Profile, which seems to be related to an earlier classpath issue.

```
2013-07-01 14:29:39,526 - [ERROR] - from org.reflections.Reflections in Default Executor-thread-9 
could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [wsjar:file:/home/nick/Programs/Websphere/wlp/usr/servers/defaultServer/workarea/org.eclipse.osgi/bundles/45/data/cache/com.ibm.ws.app.manager_gen_5b3253cc-a29a-48ff-8dbc-b3d26249b9c9/.cache/WEB-INF/lib/play.play_2.10-2.1.1.jar!/]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:108) ~[na:na]
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:90) ~[na:na]
    at org.reflections.Reflections.scan(Reflections.java:165) [na:na]
    at org.reflections.Reflections.<init>(Reflections.java:94) [na:na]
    at play.libs.Classpath.getReflections(Classpath.java:48) [na:2.1.1]
    at play.libs.Classpath.getTypes(Classpath.java:25) [na:2.1.1]
    at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:62) [na:2.1.1]
    at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:63) [na:2.1.1]
    at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:63) [na:2.1.1]
    at scala.collection.immutable.List.foreach(List.scala:309) [na:na]
    at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:63) [na:2.1.1]
    at play.api.Play$$anonfun$start$1.apply(Play.scala:63) [na:2.1.1]
    at play.api.Play$$anonfun$start$1.apply(Play.scala:63) [na:2.1.1]
    at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [na:2.1.1]
    at play.api.Play$.start(Play.scala:62) [na:2.1.1]
    at play.core.server.servlet.WarApplication.<init>(Play2Server.scala:109) [na:1.0]
    at play.core.server.servlet.Play2WarServer$.apply(Play2Server.scala:42) [na:1.0]
    at play.core.server.servlet.GenericPlay2Servlet.contextInitialized(Play2CommonServlet.scala:45) [na:1.0]
    at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2220) [com.ibm.ws.webcontainer_1.0.3.jar:na]
    at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:960) [com.ibm.ws.webcontainer_1.0.3.jar:na]
    at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:6038) [com.ibm.ws.webcontainer_1.0.3.jar:na]
    at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApp(DynamicVirtualHost.java:421) [com.ibm.ws.webcontainer_1.0.3.jar:na]
    at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.createRunnableHandler(DynamicVirtualHost.java:241) [com.ibm.ws.webcontainer_1.0.3.jar:na]
    at com.ibm.ws.http.internal.VirtualHostImpl.discriminate(VirtualHostImpl.java:182) [com.ibm.ws.transport.http_1.0.2.jar:na]
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:169) [com.ibm.ws.transport.http_1.0.2.jar:na]
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:448) [com.ibm.ws.transport.http_1.0.2.jar:na]
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:382) [com.ibm.ws.transport.http_1.0.2.jar:na]
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:282) [com.ibm.ws.transport.http_1.0.2.jar:na]
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:253) [com.ibm.ws.transport.http_1.0.2.jar:na]
    at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:174) [com.ibm.ws.channelfw_1.0.3.jar:na]
    at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:83) [com.ibm.ws.channelfw_1.0.3.jar:na]
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:502) [com.ibm.ws.channelfw_1.0.3.jar:na]
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:550) [com.ibm.ws.channelfw_1.0.3.jar:na]
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:899) [com.ibm.ws.channelfw_1.0.3.jar:na]
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:981) [com.ibm.ws.channelfw_1.0.3.jar:na]
    at com.ibm.ws.threading.internal.Worker.executeWork(Worker.java:439) [com.ibm.ws.threading_1.0.3.jar:na]
    at com.ibm.ws.threading.internal.Worker.run(Worker.java:421) [com.ibm.ws.threading_1.0.3.jar:na]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
```

**Comment by KevinSheedy** [comment]
Looks like it's a  [known issue](https://code.google.com/p/reflections/source/detail?r=169) with the reflections jar running on websphere.
It seems to be fixed in version 0.9.9-RC1 of the reflections jar.

Is that a Play issue or a Play2-war issue?

**Comment by dlecan** [comment]
> Is that a Play issue or a Play2-war issue?

Neither one nor the other, as you say, that's a Reflections issue :)

You can force Reflections version in your Play projet, in `project/Project.scala` (add the Reflections version you need as a dependency).

**Comment by dlecan** [comment]
@KevinSheedy @nickcousyn did you try with a newer Reflections version ?

**Comment by KevinSheedy** [comment]
Just tried reflections-0.9.9-RC1.jar
Looks like the class TypesScanner.java has been dropped from the reflections jar.
Got the following error:

```
[error] c.i.w.w.webapp - SRVE0283E: Exception caught while initializing context: java.lang.NoClassDefFoundError: org/reflections/scanners/TypesScanner
[ERROR   ] SRVE0777E: Exception thrown by application class 'play.core.server.servlet.Play2GenericServletRequestHandler$$anon$1.<init>:113'
java.lang.NullPointerException
    at play.core.server.servlet.Play2GenericServletRequestHandler$$anon$1.<init>(RequestHandler.scala:113)
    at play.core.server.servlet.Play2GenericServletRequestHandler.apply(RequestHandler.scala:112)
    at play.core.server.servlet.Play2WarServer$.handleRequest(Play2Server.scala:63)
    at play.core.server.servlet.GenericPlay2Servlet.service(Play2CommonServlet.scala:36)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1240)
    at [internal classes]

[error] c.i.w.w.webapp - SRVE0315E: An execption occurred: com.ibm.ws.webcontainer.webapp.WebAppErrorReport: java.lang.NullPointerException
```

**Comment by dlecan** [comment]
TypesScanner  has been removed in [rev 167](http://code.google.com/p/reflections/source/detail?r=167), but it is necessary for Play ([here](https://github.com/playframework/Play20/blob/5fb6ecf6faa58e1d427136240fa745049d2f2813/framework/src/play-java/src/main/scala/play/libs/ReflectionsCache.scala#L35), [here](https://github.com/playframework/Play20/blob/5fb6ecf6faa58e1d427136240fa745049d2f2813/framework/src/play-java/src/main/java/play/libs/Classpath.java#L25) and [here](https://github.com/playframework/Play20/blob/5fb6ecf6faa58e1d427136240fa745049d2f2813/framework/src/play-java/src/main/java/play/libs/Classpath.java#L52)).

But Websphere support in Reflections has been introduced in [rev 169](https://code.google.com/p/reflections/source/detail?r=169) :(

Play needs an upgrade of Reflections to fix this issue...

**Comment by ronmamo** [comment]
Try using TypeElementsScanner instead of TypesScanner. 
If too much of a trouble, it can be brought back in the next release

**Comment by sbarlster** [comment]
I dont mind the TypesScanner dissappearing if there is equivalent functionality available. Can you add something to the reflections lib project homepage describing how you may find all the types that are available? What the TypesScanner provided before. Do we just use the SubTypesScanner(false)?

**Comment by paulogaspar7** [comment]
Missing TypesScanner too. To the point it stops me from upgrading on some of my projects.

**Comment by dlecan** [comment]
Again, this is a Play issue. You should request an upgrade of Reflections to at least reflections-0.9.9-RC1.

**Comment by drudge** [comment]
I'm having the same issue, trying to deploy to Websphere 8.5 Liberty Profile (which says it is supported). How is it supported if this is a play issue?

**Comment by KevinSheedy** [comment]
The regression in reflections.jar is [logged here](https://code.google.com/p/reflections/issues/detail?id=150)

**Comment by tomzx** [comment]
Hey,

I'm attempting to do something similar under WebLogic 10.3.6 and getting similar results...

Play 2.1.3 with play2-war-plugin 1.0.2

```
play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.reflect.InvocationTargetException]]
    at play.api.Application$class.handleError(Application.scala:289) ~[play.play_2.10-2.1.3.jar:2.1.3]
    at play.core.server.servlet.DefaultWarApplication.handleError(Play2Server.scala:117) [com.github.play2war.play2-war-core-common_2.10-1.0.2.jar:1.0.2]
    at play.core.server.servlet.Play2GenericServletRequestHandler$$anon$2$$anonfun$handle$1$$anonfun$apply$6.apply(RequestHandler.scala:167) [com.github.play2war.play2-war-core-common_2.10-1.0.2.jar:1.0.2]
    at play.core.server.servlet.Play2GenericServletRequestHandler$$anon$2$$anonfun$handle$1$$anonfun$apply$6.apply(RequestHandler.scala:163) [com.github.play2war.play2-war-core-common_2.10-1.0.2.jar:1.0.2]
    at play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113) [play.play_2.10-2.1.3.jar:2.1.3]
    at play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113) [play.play_2.10-2.1.3.jar:2.1.3]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at play.data.Form.bind(Form.java:377) ~[play.play-java_2.10-2.1.3.jar:2.1.3]
    at play.data.Form.bindFromRequest(Form.java:215) ~[play.play-java_2.10-2.1.3.jar:2.1.3]
    at controllers.Users.login(Users.java:62) ~[myapp_2.10-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at Routes$$anonfun$routes$1$$anonfun$applyOrElse$3$$anonfun$apply$3.apply(routes_routing.scala:167) ~[myapp_2.10-1.0-SNAPSHOT.jar:na]
    at Routes$$anonfun$routes$1$$anonfun$applyOrElse$3$$anonfun$apply$3.apply(routes_routing.scala:167) ~[myapp_2.10-1.0-SNAPSHOT.jar:na]
    at play.core.Router$HandlerInvoker$$anon$6$$anon$2.invocation(Router.scala:193) ~[play.play_2.10-2.1.3.jar:2.1.3]
Caused by: java.lang.reflect.InvocationTargetException: null
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
    at play.data.Form.bind(Form.java:374) ~[play.play-java_2.10-2.1.3.jar:2.1.3]
    at play.data.Form.bindFromRequest(Form.java:215) ~[play.play-java_2.10-2.1.3.jar:2.1.3]
Caused by: javax.persistence.PersistenceException: models.User is NOT an Entity Bean registered with this server?
    at com.avaje.ebeaninternal.server.core.DefaultServer.createQuery(DefaultServer.java:989) ~[org.avaje.ebeanorm.avaje-ebeanorm-server-3.1.2.jar:na]
    at com.avaje.ebeaninternal.server.core.DefaultServer.createQuery(DefaultServer.java:946) ~[org.avaje.ebeanorm.avaje-ebeanorm-server-3.1.2.jar:na]
    at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:982) ~[org.avaje.ebeanorm.avaje-ebeanorm-server-3.1.2.jar:na]
    at play.db.ebean.Model$Finder.query(Model.java:282) ~[play.play-java-ebean_2.10-2.1.3.jar:2.1.3]
    at play.db.ebean.Model$Finder.where(Model.java:695) ~[play.play-java-ebean_2.10-2.1.3.jar:2.1.3]
    at security.UserAuthenticator.authenticate(UserAuthenticator.java:8) ~[myapp_2.10-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
```

Where any of you guys able to get it working?

**Comment by tomzx** [comment]
For anyone interested (this is about a year later now...), I was actually able to get things rolling for me by clean building, then making some config changes and finally rebuilding. See https://github.com/tomzx/play-framework-notes for more details.

**Comment by yanns** [comment]
thx for the feedback!
