### ISSUE TITLE
AbstractMethodError when added to Play 2.1.4 project

### ISSUE THREAD

**Issue by devcommunity** [play2war/play2-war-plugin#183]
Having just upgraded to the new Play 2.1.4 release, the war plugin breaks my play project when I add in this plugin, works perfectly if I remove the plugin from the various config files.

Stack:

```
$ play compile
[info] Loading project definition from /app_root/server/project
[error] java.lang.AbstractMethodError
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
...
java.lang.AbstractMethodError
    at sbt.PlayCommands$class.$init$(PlayCommands.scala:66)
    at com.github.play2war.plugin.Play2WarPlugin$.<init>(Play2WarPlugin.scala:21)
    at com.github.play2war.plugin.Play2WarPlugin$.<clinit>(Play2WarPlugin.scala)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:266)
    at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:10)
    at sbt.Load$.loadPlugin(Load.scala:586)
    at sbt.Load$$anonfun$loadPlugins$1.apply(Load.scala:583)
    at sbt.Load$$anonfun$loadPlugins$1.apply(Load.scala:583)
    at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
    at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1060)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1052)
    at scala.collection.immutable.Stream.flatMap(Stream.scala:441)
    at sbt.Load$$anonfun$pluginGlobalSettings$1.apply(Load.scala:222)
    at sbt.Load$$anonfun$pluginGlobalSettings$1.apply(Load.scala:221)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:239)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:239)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:60)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:239)
    at scala.collection.mutable.ArrayBuffer.flatMap(ArrayBuffer.scala:47)
    at sbt.Load$.pluginGlobalSettings(Load.scala:221)
    at sbt.Load$.buildConfigurations(Load.scala:194)
...
```

**Comment by kevin-lee** [comment]
I have the same issue.

```
scala: 2.10.2
sbt: 0.12.4
play: 2.1.4
play2war: 1.0
```

```
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? l
[info] Loading project definition from /home/blade2/git/kevin/kevin-home/project
[debug] Running task... Cancelable: false, check cycles: false
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] Modified external sources: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings: 
[debug]     
java.lang.AbstractMethodError
    at sbt.PlayCommands$class.$init$(PlayCommands.scala:66)
    at com.github.play2war.plugin.Play2WarPlugin$.<init>(Play2WarPlugin.scala:21)
    at com.github.play2war.plugin.Play2WarPlugin$.<clinit>(Play2WarPlugin.scala)
    at ApplicationBuild$.<init>(Build.scala:26)
    at ApplicationBuild$.<clinit>(Build.scala)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:10)
    at sbt.Load$.loadDefinition(Load.scala:550)
    at sbt.Load$$anonfun$loadDefinitions$1.apply(Load.scala:548)
    at sbt.Load$$anonfun$loadDefinitions$1.apply(Load.scala:548)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:76)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
    at scala.collection.immutable.List.map(List.scala:76)
    at sbt.Load$.loadDefinitions(Load.scala:548)
    at sbt.Load$.loadUnitNew(Load.scala:434)
    at sbt.Load$.loadUnit(Load.scala:423)
    at sbt.Load$$anonfun$13$$anonfun$apply$11.apply(Load.scala:263)
    at sbt.Load$$anonfun$13$$anonfun$apply$11.apply(Load.scala:263)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:94)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:93)
    at sbt.BuildLoader.apply(BuildLoader.scala:137)
    at sbt.Load$.loadAll(Load.scala:318)
    at sbt.Load$.loadURI(Load.scala:271)
    at sbt.Load$.load(Load.scala:267)
    at sbt.Load$.load(Load.scala:258)
    at sbt.Load$.apply(Load.scala:135)
    at sbt.Load$.defaultLoad(Load.scala:39)
    at sbt.BuiltinCommands$.doLoadProject(Main.scala:414)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:408)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:408)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
    at sbt.Command$.process(Command.scala:90)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(MainLoop.scala:71)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(MainLoop.scala:71)
    at sbt.State$$anon$2.process(State.scala:171)
    at sbt.MainLoop$$anonfun$next$1.apply(MainLoop.scala:71)
    at sbt.MainLoop$$anonfun$next$1.apply(MainLoop.scala:71)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.MainLoop$.next(MainLoop.scala:71)
    at sbt.MainLoop$.run(MainLoop.scala:64)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:53)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:50)
    at sbt.Using.apply(Using.scala:25)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:50)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:33)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:17)
    at sbt.MainLoop$.runLogged(MainLoop.scala:13)
    at sbt.xMain.run(Main.scala:26)
    at xsbt.boot.Launch$.run(Launch.scala:55)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:69)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:31)
    at xsbt.boot.Boot$.main(Boot.scala:20)
    at xsbt.boot.Boot.main(Boot.scala)
```

**Comment by dlecan** [comment]
Thank you for reporting this issue.
It's a known regression (for me):
https://groups.google.com/forum/#!msg/play-framework/Mq-rIX38la8/t2xRUCxz9eoJ

No answer from Play dev team.

It's a Scala binary incompatibility issue (2.9.x), a clean recompilation of Play2War plugin would solve this issue with Play 2.1.4
However, it would be incompatible with previous version.

**Comment by devcommunity** [comment]
Whats the best way to do that? I tried to compile and package the latest code but got a build error?

**Comment by dlecan** [comment]
> Whats the best way to do that? I tried to compile and package the latest code but got a build error?

As described here:
https://github.com/dlecan/play2-war-plugin/wiki/How-to-help#build-and-publish-plugin-and-core-runtime-in-local-repository
- Checkout Play2War source code
- Go in `project-code`
- Run `sbt publish-local`

**Comment by He-Pin** [comment]
yes,I can not using this plugin after I upgrade the Play to 2.1.4
