### ISSUE TITLE
error on play update

### ISSUE THREAD

**Issue by He-Pin** [play2war/play2-war-plugin#185]
using play 2.1.4
added 
addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.0")

```
[info] Loading project definition from /home/kerr/DevProjects/IdeaProjects/adminportal-play/project
[error] java.lang.AbstractMethodError
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? l
[info] Loading project definition from /home/kerr/DevProjects/IdeaProjects/adminportal-play/project
[debug] Running task... Cancelable: false, check cycles: false
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] Modified external sources: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] Initially invalidated: Set()
[debug] Copy resource mappings: 
[debug]     
java.lang.AbstractMethodError
    at sbt.PlayCommands$class.$init$(PlayCommands.scala:66)
    at com.github.play2war.plugin.Play2WarPlugin$.<init>(Play2WarPlugin.scala:21)
    at com.github.play2war.plugin.Play2WarPlugin$.<clinit>(Play2WarPlugin.scala)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:10)
    at sbt.Load$.loadPlugin(Load.scala:586)
    at sbt.Load$$anonfun$loadPlugins$1.apply(Load.scala:583)
    at sbt.Load$$anonfun$loadPlugins$1.apply(Load.scala:583)
    at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
    at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1060)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1052)
    at scala.collection.immutable.Stream.flatMap(Stream.scala:441)
    at sbt.Load$$anonfun$pluginGlobalSettings$1.apply(Load.scala:222)
    at sbt.Load$$anonfun$pluginGlobalSettings$1.apply(Load.scala:221)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:239)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:239)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:60)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:239)
    at scala.collection.mutable.ArrayBuffer.flatMap(ArrayBuffer.scala:47)
    at sbt.Load$.pluginGlobalSettings(Load.scala:221)
    at sbt.Load$.buildConfigurations(Load.scala:194)
    at sbt.Load$.apply(Load.scala:127)
    at sbt.Load$.defaultLoad(Load.scala:39)
    at sbt.BuiltinCommands$.doLoadProject(Main.scala:407)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:401)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:401)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
    at sbt.Command$.process(Command.scala:90)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(MainLoop.scala:71)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(MainLoop.scala:71)
    at sbt.State$$anon$2.process(State.scala:170)
    at sbt.MainLoop$$anonfun$next$1.apply(MainLoop.scala:71)
    at sbt.MainLoop$$anonfun$next$1.apply(MainLoop.scala:71)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.MainLoop$.next(MainLoop.scala:71)
    at sbt.MainLoop$.run(MainLoop.scala:64)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:53)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:50)
    at sbt.Using.apply(Using.scala:25)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:50)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:33)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:17)
    at sbt.MainLoop$.runLogged(MainLoop.scala:13)
    at sbt.xMain.run(Main.scala:26)
    at xsbt.boot.Launch$.run(Launch.scala:55)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:69)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:31)
    at xsbt.boot.Boot$.main(Boot.scala:20)
    at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.AbstractMethodError
[error] Use 'last' for the full log.

```

**Comment by dlecan** [comment]
Thank you for reporting this issue.
See this duplicated: #183
