### ISSUE TITLE
Using version 1.1 as recommended on the front page causes "unresolved dependency"

### ISSUE THREAD

**Issue by SamJoan** [play2war/play2-war-plugin#186]
Hi there,

Apologies if this is a mistake on my side.

My configuration is as follows:

_plugins.sbt_

```
addSbtPlugin("play" % "sbt-plugin" % "2.1.4")

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.1")
```

_Build.scala_

```
[...]
import com.github.play2war.plugin._
[...]
  val main = play.Project(appName, appVersion, appDependencies)
  .settings(Play2WarPlugin.play2WarSettings: _*)
  .settings(
    // Add your own project settings here      
    Play2WarKeys.servletVersion := "3.0"
  )
```

calling `play war` causes 

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.play2war#play2-war-core-servlet30_2.10;1.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.slf4j#slf4j-api;1.6.6!slf4j-api.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-core-servlet30_2.10;1.1: not found
download failed: org.slf4j#slf4j-api;1.6.6!slf4j-api.jar
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:214)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)

```

Again, sorry if this is my bad.

Cheers!
Pedro

**Comment by SimonChong** [comment]
I'm having the exact same issue. Any one?

**Comment by SimonChong** [comment]
I ended up building it as per

https://github.com/dlecan/play2-war-plugin/wiki/How-to-help

After a lot of sticky tape I got a WAR file.

**Comment by dlecan** [comment]
Maven Central synchronization is hung for Play2War.
Follow this issue to be notified when Play2War sync process will be ok:
https://issues.sonatype.org/browse/OSSRH-7262

**Comment by dlecan** [comment]
Issue is fixed (https://issues.sonatype.org/browse/OSSRH-7262?focusedCommentId=200704)
Play2war v1.1 will be available in a few hours.

**Comment by SamJoan** [comment]
Awesome work @dlecan ! Thanks

**Comment by SamJoan** [comment]
Artifact is definitively there now.

http://search.maven.org/#artifactdetails%7Ccom.github.play2war%7Cplay2-war-core-servlet25_2.10%7C1.1%7Cjar

**Comment by SimonChong** [comment]
@dlecan Great work thanks !!

**Comment by tobiasschittkowski** [comment]
Hi!

I have the same problem when using Play 2.2:

I tried 

```
addSbtPlugin("com.github.play2war" % "play2-war-core-servlet25_2.10" % "1.1")
```

and get the following error:

```
module not found: com.github.play2war#play2-war-core-servlet25_2.10;1.1
==== typesafe-ivy-releases: tried
 http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play2-war-core-servlet25_2.10/scala_2.10/sbt_0.13/1.1/ivys/ivy.xml
==== sbt-plugin-releases: tried
 http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.play2war/play2-war-core-servlet25_2.10/scala_2.10/sbt_0.13/1.1/ivys/ivy.xml
==== sonatype-oss-snapshots: tried
 http://oss.sonatype.org/content/repositories/snapshots/com/github/play2war/play2-war-core-servlet25_2.10_2.10_0.13/1.1/play2-war-core-servlet25_2
==== public: tried
 http://repo1.maven.org/maven2/com/github/play2war/play2-war-core-servlet25_2.10_2.10_0.13/1.1/play2-war-core-servlet25_2.10-1.1.pom
==== Typesafe repository: tried
 http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-core-servlet25_2.10_2.10_0.13/1.1/play2-war-core-servlet25_2.10-1.1.pom

Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
        com.github.play2war:play2-war-core-servlet25_2.10:1.1 (sbtVersion=0.13, scalaVersion=2.10)

```

Thank you for your support!
Regards,
Tobias

**Comment by dlecan** [comment]
@tobiasschittkowski Play2War is totally broken by new Play 2.2 APIs and SBT 0.13 upgrade.
Watch #188 to follow Play2War updates.

**Comment by tobiasschittkowski** [comment]
Thank you for your quick response!
