### ISSUE TITLE
JBoss logging stops when deploying play app war

### ISSUE THREAD

**Issue by sigma-wschung** [play2war/play2-war-plugin#197]
I am trying to deploy a play 2.1.2 app war file to JBoss 7.2.0. I have followed the instruction to configure loggng in JBoss 7 and added the redirect dependency to Build.scala:

``` scala
...
  val appDependencies = Seq(
    // Add your project dependencies here,
    javaCore,
    javaJdbc,
    javaEbean,
    "com.github.play2war.ext" %% "redirect-playlogger" % "1.0.1"
  )
  //cache

  val main = play.Project(appName, appVersion, appDependencies)
      .settings(Play2WarPlugin.play2WarSettings: _*)
      // Add your own project settings here      
      .settings(Play2WarKeys.servletVersion := "3.0",
                Play2WarKeys.targetName := Some(appName)
       )
...
```

About half the time during the deployment of this play App with other non-play app, the JBoss server.log stops logging anything after showing this:

```
10:31:25,364 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-15) JBAS010403: Deploying JDBC-compliant driver class oracle.jdbc.OracleDriver (version 11.2)
10:31:25,445 INFO  [org.jboss.web] (ServerService Thread Pool -- 68) JBAS018210: Register web context: /adminweb
10:31:25,597 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/adminweb]] (ServerService Thread Pool -- 68) PlayServletWrapper > contextInitialized
10:31:26,019 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (MSC service thread 1-15) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evic
ted entities will be passivated.
10:31:26,020 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (MSC service thread 1-16) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evic
ted entities will be passivated.
10:31:26,025 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (MSC service thread 1-15) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evic
ted entities will be passivated.
10:31:26,025 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (MSC service thread 1-16) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evic
ted entities will be passivated.
10:31:26,026 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (MSC service thread 1-7) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evict
ed entities will be passivated.
10:31:26,027 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (MSC service thread 1-7) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evict
ed entities will be passivated.
10:31:26,061 TRACE [org.jboss.modules] (ServerService Thread Pool -- 68) Finding class scala.collection.mutable.ArrayOps$ofRef from Module "deployment.adminweb.war:main" from Service Module Loader
10:31:26,061 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Defined class org.infinispan.commands.remote.MultipleRpcCommand in Module "org.infinispan:main" from local module loader @cea9d22 (fin
der: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,062 TRACE [org.jboss.modules] (ServerService Thread Pool -- 68) Finding local class scala.collection.mutable.ArrayOps$ofRef from Module "deployment.adminweb.war:main" from Service Module Loader
10:31:26,062 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Finding class org.infinispan.commands.tx.CommitCommand from Module "org.infinispan:main" from local module loader @cea9d22 (finder: lo
cal module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,062 TRACE [org.jboss.modules] (ServerService Thread Pool -- 68) Loading class scala.collection.mutable.ArrayOps$ofRef locally from Module "deployment.adminweb.war:main" from Service Module Loader
10:31:26,062 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Finding local class org.infinispan.commands.tx.CommitCommand from Module "org.infinispan:main" from local module loader @cea9d22 (find
er: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,062 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Loading class org.infinispan.commands.tx.CommitCommand locally from Module "org.infinispan:main" from local module loader @cea9d22 (fi
nder: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,062 TRACE [org.jboss.modules] (ServerService Thread Pool -- 68) Attempting to define class scala.collection.mutable.ArrayOps$ofRef in Module "deployment.adminweb.war:main" from Service Module Loader
10:31:26,062 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Attempting to define class org.infinispan.commands.tx.CommitCommand in Module "org.infinispan:main" from local module loader @cea9d22
(finder: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,063 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Defined class org.infinispan.commands.tx.CommitCommand in Module "org.infinispan:main" from local module loader @cea9d22 (finder: loca
l module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,063 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Finding class org.infinispan.commands.tx.PrepareCommand from Module "org.infinispan:main" from local module loader @cea9d22 (finder: l
ocal module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,063 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Finding local class org.infinispan.commands.tx.PrepareCommand from Module "org.infinispan:main" from local module loader @cea9d22 (fin
der: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,064 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Loading class org.infinispan.commands.tx.PrepareCommand locally from Module "org.infinispan:main" from local module loader @cea9d22 (f
inder: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,064 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Attempting to define class org.infinispan.commands.tx.PrepareCommand in Module "org.infinispan:main" from local module loader @cea9d22
 (finder: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,065 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Defined class org.infinispan.commands.tx.PrepareCommand in Module "org.infinispan:main" from local module loader @cea9d22 (finder: loc
al module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,065 TRACE [org.jboss.modules] (ServerService Thread Pool -- 68) Defined class scala.collection.mutable.ArrayOps$ofRef in Module "deployment.adminweb.war:main" from Service Module Loader
10:31:26,065 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Finding class org.infinispan.commands.tx.RollbackCommand from Module "org.infinispan:main" from local module loader @cea9d22 (finder:
local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,065 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Finding local class org.infinispan.commands.tx.RollbackCommand from Module "org.infinispan:main" from local module loader @cea9d22 (fi
...
10:31:26,071 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Defined class org.infinispan.commands.remote.recovery.RecoveryCommand in Module "org.infinispan:main" from local module loader @cea9d22 (finder: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,071 TRACE [org.jboss.modules] (ServerService Thread Pool -- 68) Defined class scala.collection.mutable.ArrayOps$ofRef$ in Module "deployment.adminweb.war:main" from Service Module Loader
10:31:26,071 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Defined class org.infinispan.commands.remote.recovery.TxCompletionNotificationCommand in Module "org.infinispan:main" from local module loader @cea9d22 (finder: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,072 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Finding class org.infinispan.commands.remote.recovery.GetInDoubtTransactionsCommand from Module "org.infinispan:main" from local module loader @cea9d22 (finder: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,072 TRACE [org.jboss.modules] (ServerService Thread Pool -- 68) Finding class scala.runtime.BoxedUnit from Module "deployment.adminweb.war:main" from Service Module Loader
10:31:26,072 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Finding local class org.infinispan.commands.remote.recovery.GetInDoubtTransactionsCommand from Module "org.infinispan:main" from local module loader @cea9d22 (finder: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,072 TRACE [org.jboss.modules] (ServerService Thread Pool -- 68) Finding local class scala.runtime.BoxedUnit from Module "deployment.adminweb.war:main" from Service Module Loader
10:31:26,072 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Loading class org.infinispan.commands.remote.recovery.GetInDoubtTransactionsCommand locally from Module "org.infinispan:main" from local module loader @cea9d22 (finder: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,072 TRACE [org.jboss.modules] (ServerService Thread Pool -- 68) Loading class scala.runtime.BoxedUnit locally from Module "deployment.adminweb.war:main" from Service Module Loader
10:31:26,072 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Attempting to define class org.infinispan.commands.remote.recovery.GetInDoubtTransactionsCommand in Module "org.infinispan:main" from local module loader @cea9d22 (finder: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
10:31:26,072 TRACE [org.jboss.modules] (ServerService Thread Pool -- 68) Attempting to define class scala.runtime.BoxedUnit in Module "deployment.adminweb.war:main" from Service Module Loader
10:31:26,073 TRACE [org.jboss.modules] (ServerService Thread Pool -- 68) Defined class scala.runtime.BoxedUnit in Module "deployment.adminweb.war:main" from Service Module Loader
10:31:26,073 TRACE [org.jboss.modules] (ServerService Thread Pool -- 64) Defined class org.infinispan.commands.remote.recovery.GetInDoubtTransactionsCommand in Module "org.infinispan:main" from local module loader @cea9d22 (finder: local module finder @7ef229cd (roots: /nfs/home/waishing/clustering-domains-14/jboss-perf/modules,/nfs/tools/jboss/6.1.0/modules,/nfs/tools/jboss/6.1.0/modules/system/layers/base))
```

When the server startups correctly, only the line:

PlayServletWrapper > contextInitialized

is shown. There is no Finding class scala.collection.mutable.... line shown.

It seems like some timing issue, like issue 133.

**Comment by sigma-wschung** [comment]
I forget to mention that this issue appears to have cause other application to not startup correctly. The play app does startup and is accepting request, although all responses come back as error page. Since there is no log, I cannot tells whether the error is due to the play app or from because of the other app.

**Comment by sigma-wschung** [comment]
After some more tries, it turns out this issue is not related to the non-play app. Just the play app deployed to JBoss is giving the same behavior.

**Comment by sigma-wschung** [comment]
I notice that the debug level was switched to display some TRACE level output, while when the issue does not happen, the log level stays at INFO. This seem to be consistent with what the two lines of code in play.api.Logger pointed out in #54 that could cause the server.log to stop. I also notice that the class  Logger$$anonfun$configure$1$$anonfun$apply$1 is being loaded by JBoss. I try removing this class from the play jar in the war file. I get this stack trace. This seem to be consistent with the call stack based on the code, if the redirect plugin is not present. The log level is also switched up when this stack trace happen. Could you explain how the redirect plugin works? It almost looks like the war plugin and the redirect plugin are loaded in parallel and some times the redirect plugin is not in effect before the play2war plugin is already initialized.

```
ESC[0mESC[31m20:26:00,749 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/smpadmin]] (ServerService Thread Pool -- 61) JBWEB000287: Exception sending context initialized
event to listener instance of class play.core.server.servlet30.Play2Servlet: java.lang.NoClassDefFoundError: play/api/Logger$$anonfun$configure$1$$anonfun$apply$1
        at play.api.Logger$$anonfun$configure$1.apply(Logger.scala:213) [play.play_2.10-2.1.2.jar:]
        at play.api.Logger$$anonfun$configure$1.apply(Logger.scala:211) [play.play_2.10-2.1.2.jar:]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.0.jar:]
        at play.api.Logger$.configure(Logger.scala:211) [play.play_2.10-2.1.2.jar:]
        at play.core.server.servlet.Play2WarServer$.<init>(Play2Server.scala:46) [com.github.play2war.play2-war-core-common_2.10-1.0.jar:1.0]
        at play.core.server.servlet.Play2WarServer$.<clinit>(Play2Server.scala) [com.github.play2war.play2-war-core-common_2.10-1.0.jar:1.0]
        at play.core.server.servlet.GenericPlay2Servlet.contextInitialized(Play2CommonServlet.scala:45) [com.github.play2war.play2-war-core-common_2.10-1.0.jar:1.0]
        at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3339) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
```

...

**Comment by dlecan** [comment]
Thank you for reporting all these information.

"redirect plugin" provides `Logger` class and object with an empty configuration implementation (compared to Play 2 one). See https://github.com/dlecan/redirect-playlogger/blob/develop/src/main/scala/Logger.scala.
When the redirect plugin is enabled, you should see "Play logs now directly handled by this application server" in logs.

In order to work, "redirect plugin" must be loaded **before** main Play jar in the classpath. Usually, jars are loaded in alphabetical order, so it's fine, because `com.github.play2war.ext.redirect-playlogger-xx.jar` is "before" `play-XX.jar` in classpath.

**Comment by sigma-wschung** [comment]
I tried starting the server a few times. Every time the log continue without stopping, the line "Play logs now directly handled by this application server" is written out in the log. Every time the log stops, this line is not in the log. It seems clear that the Logger class in the redirect-plugin is not always run and the fact it is not used is the cause of the log being stopped.

I see that the Logger class in the redirect-pluing in jar file "com.github.play2war.ext.redirect-playlogger_2.10-1.0.1.jar" and that in the play jar file "play.play_2.10-2.1.2.jar" both have the fully-qualifed name play.api.Logger. So the redirect-plugin is used or not depends on whether the class loader really follows the alphabetical order of the jar files. It looks like JBoss 7.2 is not loading the classes in this order, and not even in a deterministic manner. I hope JBoss provides more control on the order of class loading.

**Comment by sigma-wschung** [comment]
Here is a simple workaround that I find works. Since the problem is that JBoss is loading the Logger class from the play jar instead of the redirect plugin some time, I unzip the generated war file and the play jar file play.play_2.10-2.1.2.jar and then delete the two class files that have the same package and class name as those in the redirect plugin jar file com.github.play2war.ext.redirect-playlogger_2.10-1.0.1.jar(ie. play.api.Logger.class and play.api.Logger$.class) and repackage and jar and war file. After that I have restarted my JBoss server over 20 times, both in standalone and domain mode. The log file never stops again.

**Comment by pasamio** [comment]
I ran into a similar problem and the solution provided by @sigma-wschung worked properly. Thanks!
