### ISSUE TITLE
Unresolved dependency: com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT

### ISSUE THREAD

**Issue by adelarsq** [play2war/play2-war-plugin#210]
The command  "play war" in the sample (play2-war-plugin/sample) didnt work, showing the log:

```
C:\dev\workspace\play\play2-war-plugin\sample>set HTTP_PROXY=http://192.168.0.1:128
C:\dev\workspace\play\play2-war-plugin\sample>set HTTPS_PROXY=http://192.168.0.1:128
C:\dev\workspace\play\play2-war-plugin\sample>play war
[info] Loading project definition from C:\dev\workspace\play\play2-war-plugin\sample\project
[info] Set current project to a-play2war-sample-parent (in build file:/C:/dev/workspace/play/play2-war-plugin/sample/)
[info] Updating {file:/C:/dev/workspace/play/play2-war-plugin/sample/}a-play2war-sample-servlet30...
[info] Updating {file:/C:/dev/workspace/play/play2-war-plugin/sample/}a-play2war-sample-servlet25...
[info] Wrote C:\dev\workspace\play\play2-war-plugin\sample\servlet25\target\scala-2.10\a-play2war-sample-servlet25_2.10-1.0-SNAPSHOT.pom
[info] Resolving org.scala-lang#scala-library;2.10.2 ...
[info] Resolving a-play2war-sample-common#a-play2war-sample-common_2.10;1.0-SNAPSHOT ...
[info] Resolving com.typesafe.play#play_2.10;2.2.1 ...
[info] Resolving com.typesafe.play#sbt-link;2.2.1 ...
[info] Resolving org.javassist#javassist;3.18.0-GA ...
[info] Resolving com.typesafe.play#play-exceptions;2.2.1 ...
 [info] Resolving com.typesafe.play#templates_2.10;2.2.1 ...
 [info] Resolving com.github.scala-incubator.io#scala-io-file_2.10;0.4.2 ...
 [info] Resolving com.github.scala-incubator.io#scala-io-core_2.10;0.4.2 ...
[info] Resolving com.jsuereth#scala-arm_2.10;1.3 ...
[info] Resolving com.typesafe.play#play-iteratees_2.10;2.2.1 ...
[info] Resolving org.scala-stm#scala-stm_2.10;0.7 ...
[info] Resolving com.typesafe#config;1.0.2 ...
 [info] Resolving com.typesafe.play#play-json_2.10;2.2.1 ...
 [info] Resolving com.typesafe.play#play-functional_2.10;2.2.1 ...
 [info] Resolving com.typesafe.play#play-datacommons_2.10;2.2.1 ...
 [info] Resolving joda-time#joda-time;2.2 ...
 [info] Resolving org.joda#joda-convert;1.3.1 ...
 [info] Resolving com.fasterxml.jackson.core#jackson-annotations;2.2.2 ...
 [info] Resolving com.fasterxml.jackson.core#jackson-core;2.2.2 ...
 [info] Resolving com.fasterxml.jackson.core#jackson-databind;2.2.2 ...
 [info] Resolving org.scala-lang#scala-reflect;2.10.2 ...
[info] Resolving io.netty#netty;3.7.0.Final ...
[info] Resolving com.typesafe.netty#netty-http-pipelining;1.1.2 ...
[info] Resolving org.slf4j#slf4j-api;1.7.5 ...
 [info] Resolving org.slf4j#jul-to-slf4j;1.7.5 ...
[info] Resolving org.slf4j#jcl-over-slf4j;1.7.5 ...
[info] Resolving ch.qos.logback#logback-core;1.0.13 ...
[info] Resolving ch.qos.logback#logback-classic;1.0.13 ...
[info] Resolving com.typesafe.akka#akka-actor_2.10;2.2.0 ...
 [info] Resolving com.typesafe.akka#akka-slf4j_2.10;2.2.0 ...
 [info] Resolving org.apache.commons#commons-lang3;3.1 ...
 [info] Resolving com.ning#async-http-client;1.7.18 ...
 [info] Resolving oauth.signpost#signpost-core;1.2.1.2 ...
[info] Resolving commons-codec#commons-codec;1.3 ...
[info] Resolving oauth.signpost#signpost-commonshttp4;1.2.1.2 ...
[info] Resolving org.apache.httpcomponents#httpcore;4.0.1 ...
 [info] Resolving org.apache.httpcomponents#httpclient;4.0.1 ...
 [info] Resolving commons-logging#commons-logging;1.1.1 ...
[info] Resolving xerces#xercesImpl;2.11.0 ...
[info] Resolving xml-apis#xml-apis;1.4.01 ...
[info] Resolving org.scala-lang#scala-library;2.10.2 ...
[info] Resolving a-play2war-sample-common#a-play2war-sample-common_2.10;1.0-SNAPSHOT ...
[info] Resolving com.typesafe.play#play_2.10;2.2.1 ...
 [info] Resolving com.typesafe.play#sbt-link;2.2.1 ...
 [info] Resolving org.javassist#javassist;3.18.0-GA ...
 [info] Resolving com.typesafe.play#play-exceptions;2.2.1 ...
 [info] Resolving com.typesafe.play#templates_2.10;2.2.1 ...
 [info] Resolving com.github.scala-incubator.io#scala-io-file_2.10;0.4.2 ...
[info] Resolving com.github.scala-incubator.io#scala-io-core_2.10;0.4.2 ...
 [info] Resolving com.jsuereth#scala-arm_2.10;1.3 ...
 [info] Resolving com.typesafe.play#play-iteratees_2.10;2.2.1 ...
 [info] Resolving org.scala-stm#scala-stm_2.10;0.7 ...
 [info] Resolving com.typesafe#config;1.0.2 ...
 [info] Resolving com.typesafe.play#play-json_2.10;2.2.1 ...
 [info] Resolving com.typesafe.play#play-functional_2.10;2.2.1 ...
 [info] Resolving com.typesafe.play#play-datacommons_2.10;2.2.1 ...
 [info] Resolving joda-time#joda-time;2.2 ...
 [info] Resolving org.joda#joda-convert;1.3.1 ...
 [info] Resolving com.fasterxml.jackson.core#jackson-annotations;2.2.2 ...
 [info] Resolving com.fasterxml.jackson.core#jackson-core;2.2.2 ...
 [info] Resolving com.fasterxml.jackson.core#jackson-databind;2.2.2 ...
 [info] Resolving org.scala-lang#scala-reflect;2.10.2 ...
 [info] Resolving io.netty#netty;3.7.0.Final ...
 [info] Resolving com.typesafe.netty#netty-http-pipelining;1.1.2 ...
 [info] Resolving org.slf4j#slf4j-api;1.7.5 ...
 [info] Resolving org.slf4j#jul-to-slf4j;1.7.5 ...
 [info] Resolving org.slf4j#jcl-over-slf4j;1.7.5 ...
 [info] Resolving ch.qos.logback#logback-core;1.0.13 ...
 [info] Resolving ch.qos.logback#logback-classic;1.0.13 ...
 [info] Resolving com.typesafe.akka#akka-actor_2.10;2.2.0 ...
 [info] Resolving com.typesafe.akka#akka-slf4j_2.10;2.2.0 ...
 [info] Resolving org.apache.commons#commons-lang3;3.1 ...
 [info] Resolving com.ning#async-http-client;1.7.18 ...
 [info] Resolving oauth.signpost#signpost-core;1.2.1.2 ...
[info] Resolving commons-codec#commons-codec;1.3 ...
 [info] Resolving oauth.signpost#signpost-commonshttp4;1.2.1.2 ...
[info] Resolving org.apache.httpcomponents#httpcore;4.0.1 ...
 [info] Resolving org.apache.httpcomponents#httpclient;4.0.1 ...
 [info] Resolving commons-logging#commons-logging;1.1.1 ...
[info] Resolving xerces#xercesImpl;2.11.0 ...
[info] Resolving xml-apis#xml-apis;1.4.01 ...
[info] Resolving javax.transaction#jta;1.1 ...
 [info] Resolving com.typesafe.play#play-java_2.10;2.2.1 ...
 [info] Resolving org.yaml#snakeyaml;1.12 ...
 [info] Resolving org.hibernate#hibernate-validator;5.0.1.Final ...
[info] Resolving javax.validation#validation-api;1.1.0.Final ...
 [info] Resolving org.jboss.logging#jboss-logging;3.1.1.GA ...
 [info] Resolving com.fasterxml#classmate;0.8.0 ...
[info] Resolving org.springframework#spring-context;3.2.3.RELEASE ...
 [info] Resolving org.springframework#spring-core;3.2.3.RELEASE ...
 [info] Resolving org.springframework#spring-beans;3.2.3.RELEASE ...
 [info] Resolving org.reflections#reflections;0.9.8 ...
 [info] Resolving com.google.guava#guava;14.0.1 ...
 [info] Resolving com.google.code.findbugs#jsr305;2.0.1 ...
 [info] Resolving javax.servlet#javax.servlet-api;3.0.1 ...
 [info] Resolving com.github.play2war.ext#redirect-playlogger_2.10;1.0.1 ...
 [info] Resolving com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT ...
[error] Server access Error: Connection timed out: connect url=https://oss.sonatype.org/content/repositories/snapshots/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/maven-metadata.xml
[error] Server access Error: Connection timed out: connect url=https://oss.sonatype.org/content/repositories/snapshots/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
[warn]  module not found: com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT
[warn] ==== local: tried
[warn]   C:\dev\play-2.2.1\repository\local\com.github.play2war\play2-war-core-servlet30_2.10\1.2-beta3-SNAPSHOT\ivys\ivy.xml
[warn] ==== Maven2 Local: tried
[warn]   file:/C:/Users/DES00015/.m2/repository/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
[warn] ==== Typesafe Releases Repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
[warn] ==== Typesafe Releases Repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
[warn] ==== Local Ivy Repository: tried
[warn]   C:\Users\DES00015\.ivy2\local\com.github.play2war\play2-war-core-servlet30_2.10\1.2-beta3-SNAPSHOT\ivys\ivy.xml
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
[info] Resolving com.typesafe.play#play-test_2.10;2.2.1 ...
 [info] Resolving junit#junit;4.11 ...
[info] Resolving org.hamcrest#hamcrest-core;1.3 ...
[info] Resolving org.specs2#specs2_2.10;2.1.1 ...
[info] Resolving org.scalaz#scalaz-core_2.10;7.0.2 ...
 [info] Resolving org.scalaz#scalaz-concurrent_2.10;7.0.2 ...
 [info] Resolving org.scalaz#scalaz-effect_2.10;7.0.2 ...
 [info] Resolving com.novocode#junit-interface;0.10 ...
[info] Resolving org.scala-tools.testing#test-interface;0.5 ...
[info] Resolving org.fluentlenium#fluentlenium-festassert;0.8.0 ...
[info] Resolving org.fluentlenium#fluentlenium-core;0.8.0 ...
 [info] Resolving org.seleniumhq.selenium#selenium-java;2.32.0 ...
 [info] Resolving org.seleniumhq.selenium#selenium-android-driver;2.32.0 ...
 [info] Resolving org.seleniumhq.selenium#selenium-remote-driver;2.32.0 ...
 [info] Resolving cglib#cglib-nodep;2.1_3 ...
[info] Resolving org.json#json;20080701 ...
 [info] Resolving org.seleniumhq.selenium#selenium-api;2.32.0 ...
 [info] Resolving org.apache.httpcomponents#httpclient;4.2.1 ...
 [info] Resolving org.apache.httpcomponents#httpcore;4.2.1 ...
 [info] Resolving commons-codec#commons-codec;1.6 ...
 [info] Resolving org.apache.commons#commons-exec;1.1 ...
 [info] Resolving net.java.dev.jna#jna;3.4.0 ...
 [info] Resolving net.java.dev.jna#platform;3.4.0 ...
 [info] Resolving org.seleniumhq.selenium#selenium-chrome-driver;2.32.0 ...
 [info] Resolving org.seleniumhq.selenium#selenium-htmlunit-driver;2.32.0 ...
 [info] Resolving net.sourceforge.htmlunit#htmlunit;2.12 ...
 [info] Resolving xalan#xalan;2.7.1 ...
 [info] Resolving xalan#serializer;2.7.1 ...
 [info] Resolving commons-collections#commons-collections;3.2.1 ...
 [info] Resolving org.apache.httpcomponents#httpmime;4.2.3 ...
 [info] Resolving net.sourceforge.htmlunit#htmlunit-core-js;2.12 ...
 [info] Resolving net.sourceforge.nekohtml#nekohtml;1.9.18 ...
 [info] Resolving net.sourceforge.cssparser#cssparser;0.9.9 ...
 [info] Resolving org.w3c.css#sac;1.3 ...
 [info] Resolving commons-io#commons-io;2.2 ...
 [info] Resolving org.eclipse.jetty#jetty-websocket;8.1.9.v20130131 ...
 [info] Resolving org.eclipse.jetty#jetty-util;8.1.9.v20130131 ...
 [info] Resolving org.eclipse.jetty#jetty-io;8.1.9.v20130131 ...
 [info] Resolving org.eclipse.jetty#jetty-http;8.1.9.v20130131 ...
 [info] Resolving org.seleniumhq.selenium#selenium-firefox-driver;2.32.0 ...
 [info] Resolving org.seleniumhq.selenium#selenium-ie-driver;2.32.0 ...
 [info] Resolving org.seleniumhq.selenium#selenium-iphone-driver;2.32.0 ...
 [info] Resolving org.seleniumhq.selenium#selenium-safari-driver;2.32.0 ...
 [info] Resolving org.webbitserver#webbit;0.4.14 ...
 [info] Resolving org.seleniumhq.selenium#selenium-support;2.32.0 ...
 [info] Resolving org.easytesting#fest-assert;1.4 ...
 [info] Resolving org.easytesting#fest-util;1.1.6 ...
[info] Wrote C:\dev\workspace\play\play2-war-plugin\sample\servlet30\target\scala-2.10\a-play2war-sample-servlet30_2.10-1.0-SNAPSHOT.pom
[info] Wrote C:\dev\workspace\play\play2-war-plugin\sample\common\target\scala-2.10\a-play2war-sample-common_2.10-1.0-SNAPSHOT.pom
sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:213)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:104)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:51)
        at sbt.IvySbt$$anon$3.call(Ivy.scala:60)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
        at xsbt.boot.Using$.withResource(Using.scala:11)
        at xsbt.boot.Using$.apply(Using.scala:10)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:60)
        at sbt.IvySbt.withIvy(Ivy.scala:101)
        at sbt.IvySbt.withIvy(Ivy.scala:97)
        at sbt.IvySbt$Module.withModule(Ivy.scala:116)
        at sbt.IvyActions$.update(IvyActions.scala:121)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1144)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1142)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$73.apply(Defaults.scala:1165)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$73.apply(Defaults.scala:1163)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1167)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1162)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1170)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1135)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1113)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-core-servlet25_2.10;1.2-beta3-SNAPSHOT: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:213)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:104)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:51)
        at sbt.IvySbt$$anon$3.call(Ivy.scala:60)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
        at xsbt.boot.Using$.withResource(Using.scala:11)
        at xsbt.boot.Using$.apply(Using.scala:10)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:60)
        at sbt.IvySbt.withIvy(Ivy.scala:101)
        at sbt.IvySbt.withIvy(Ivy.scala:97)
        at sbt.IvySbt$Module.withModule(Ivy.scala:116)
        at sbt.IvyActions$.update(IvyActions.scala:121)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1144)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1142)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$73.apply(Defaults.scala:1165)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$73.apply(Defaults.scala:1163)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1167)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1162)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1170)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1135)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1113)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
[error] (a-play2war-sample-servlet30/*:update) sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT: not found
[error] (a-play2war-sample-servlet25/*:update) sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-core-servlet25_2.10;1.2-beta3-SNAPSHOT: not found
[error] Total time: 114 s, completed 26/12/2013 11:41:55
```

Running "last a-play2war-sample-servlet30/*:update" shows:

```
...
[debug] == resolving dependencies a-play2war-sample-servlet30#a-play2war-sample-servlet30_2.10;1.0-SNAPSHOT->com.github.play2war.ext#redirect-playlogger_2.10;1.0.1 [compile->master] [debug] == resolving dependencies a-play2war-sample-servlet30#a-play2war-sample-servlet30_2.10;1.0-SNAPSHOT->com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT [compile->default(compile)]
[info] Resolving com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT ...
[debug] sbt-chain: Checking cache for: dependency: com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT {compile=[default(compile)]}
[debug] don't use cache for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT: changing=true
[debug] don't use cache for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT: changing=true
[debug]                 tried C:\dev\play-2.2.1\repository\local\com.github.play2war\play2-war-core-servlet30_2.10\1.2-beta3-SNAPSHOT\ivys\ivy.xml
[debug]         local: no ivy file found for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT
[debug] don't use cache for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT: changing=true
[debug]         maven-metadata not available: file:/C:/Users/DES00015/.m2/repository/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/maven-metadata.xml
[debug]                 tried file:/C:/Users/DES00015/.m2/repository/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
[debug]         Maven2 Local: no ivy file found for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT
[debug] don't use cache for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT: changing=true
[debug] CLIENT ERROR: Not Found url=http://repo1.maven.org/maven2/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/maven-metadata.xml
[debug]         maven-metadata not available: http://repo1.maven.org/maven2/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/maven-metadata.xml
[debug]                 tried http://repo1.maven.org/maven2/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom [debug] CLIENT ERROR: Not Found url=http://repo1.maven.org/maven2/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
[debug]         public: no ivy file found for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT
[debug] don't use cache for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT: changing=true
[debug] CLIENT ERROR: Not Found url=http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/maven-metadata.xml
[debug]         maven-metadata not available: http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/maven-metadata.xml
[debug]                 tried http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
[debug] CLIENT ERROR: Not Found url=http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
[debug]         Typesafe Releases Repository: no ivy file found for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT
[debug] don't use cache for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT: changing=true
[debug] CLIENT ERROR: Not Found url=http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/maven-metadata.xml
[debug]         maven-metadata not available: http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/maven-metadata.xml
[debug]                 tried http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
[debug] CLIENT ERROR: Not Found url=http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
[debug]         Typesafe Releases Repository: no ivy file found for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT
[debug] don't use cache for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT: changing=true
[debug]                 tried C:\Users\DES00015\.ivy2\local\com.github.play2war\play2-war-core-servlet30_2.10\1.2-beta3-SNAPSHOT\ivys\ivy.xml
[debug]         Local Ivy Repository: no ivy file found for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT
[debug] don't use cache for com.github.play2war#play2-war-core-servlet30_2.10;1.2-beta3-SNAPSHOT: changing=true
[error] Server access Error: Connection timed out: connect url=https://oss.sonatype.org/content/repositories/snapshots/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/maven-metadata.xml
[debug]         maven-metadata not available: https://oss.sonatype.org/content/repositories/snapshots/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/maven-metadata.xml
[debug]                 tried https://oss.sonatype.org/content/repositories/snapshots/com/github/play2war/play2-war-core-servlet30_2.10/1.2-beta3-SNAPSHOT/play2-war-core-servlet30_2.10-1.2-beta3-SNAPSHOT.pom
...
```

It's related with some configuration that I am forgetting?

Setup:
Play 2.2.1
JDK 1.7.0_45 (Windows x64)

**Comment by dlecan** [comment]
You have to deploy play2war locally before building the sample. For your configuration, in `C:\dev\workspace\play\play2-war-plugin\project-code`, run `sbt publish-local`.

What do you want to do ?

**Comment by adelarsq** [comment]
Did work! The first time that I executed the command showed a error like from http://stackoverflow.com/questions/18505176/unresolved-dependency-sbt-0-13-0-after-update
Worked after do upgrade from SBT.
I want create a Play application (packaged as a war) to manipule JMS queues inside a JBoss 7 Server.
Thanks @dlecan
