### ISSUE TITLE
Play2War can't be installed and run offline

### ISSUE THREAD

**Issue by mountash** [play2war/play2-war-plugin#211]
```
...projectName>play war
[info] Loading project definition from ...projectName\project
[info] Set current project to Hub (in build file:...projectName/)
[info] Wrote ...projectName\modules\common\target\scala-2.10\common_2.10-1.0-SNAPSHOT.pom
[info] Wrote ...projectName\modules\platform\target\scala-2.10\platform_2.10-1.0-SNAPSHOT.pom
[info] Wrote ...projectName\modules\fxrates\target\scala-2.10\rates_2.10-1.0-SNAPSHOT.pom
[info] Build WAR package for servlet container: 2.5
[error] play2-war-core-common not found in dependencies!
[info] Build WAR package for servlet container: 2.5
[error] play2-war-core-common not found in dependencies!
[info] Build WAR package for servlet container: 2.5
[error] play2-war-core-common not found in dependencies!
java.lang.IllegalArgumentException: play2-war-core-common not found in dependencies!
        at com.github.play2war.plugin.Play2WarCommands$$anonfun$1.apply(Play2WarCommands.scala:59)
        at com.github.play2war.plugin.Play2WarCommands$$anonfun$1.apply(Play2WarCommands.scala:47)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.IllegalArgumentException: play2-war-core-common not found in dependencies!
        at com.github.play2war.plugin.Play2WarCommands$$anonfun$1.apply(Play2WarCommands.scala:59)
        at com.github.play2war.plugin.Play2WarCommands$$anonfun$1.apply(Play2WarCommands.scala:47)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.IllegalArgumentException: play2-war-core-common not found in dependencies!
        at com.github.play2war.plugin.Play2WarCommands$$anonfun$1.apply(Play2WarCommands.scala:59)
        at com.github.play2war.plugin.Play2WarCommands$$anonfun$1.apply(Play2WarCommands.scala:47)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (Rates/*:war) java.lang.IllegalArgumentException: play2-war-core-common not found in dependencies!
[error] (Platform/*:war) java.lang.IllegalArgumentException: play2-war-core-common not found in dependencies!
[error] (Common/*:war) java.lang.IllegalArgumentException: play2-war-core-common not found in dependencies!
[error] Total time: 3 s, completed 29.12.2013 0:27:20
```

**Comment by mountash** [comment]
Unfortunately it can`t work offline. When running on server with Internet connection all compiled. War created.
Deployed and run on tomcat 6. But when trying to open the url an error appears: 

```
exception 
javax.servlet.ServletException: Servlet execution threw an exception
root cause 
java.lang.UnsatisfiedLinkError: sun/misc/Unsafe.putOrderedObject(Ljava/lang/Object;JLjava/lang/Object;)V
    scala.concurrent.forkjoin.ForkJoinPool.fullExternalPush(ForkJoinPool.java:1897)
    scala.concurrent.forkjoin.ForkJoinPool.externalPush(ForkJoinPool.java:1834)
    scala.concurrent.forkjoin.ForkJoinPool.execute(ForkJoinPool.java:2955)
    akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinPool.execute(AbstractDispatcher.scala:374)
    akka.dispatch.ExecutorServiceDelegate$class.execute(ThreadPoolBuilder.scala:212)
    akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.execute(Dispatcher.scala:43)
    akka.dispatch.Dispatcher.registerForExecution(Dispatcher.scala:118)
    akka.dispatch.MessageDispatcher.attach(AbstractDispatcher.scala:134)
    akka.actor.dungeon.Dispatch$class.start(Dispatch.scala:84)
    akka.actor.ActorCell.start(ActorCell.scala:338)
    akka.actor.LocalActorRef.start(ActorRef.scala:321)
    akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:619)
    akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:579)
    akka.actor.ActorSystemImpl._start(ActorSystem.scala:577)
    akka.actor.ActorSystemImpl.start(ActorSystem.scala:588)
    akka.actor.ActorSystem$.apply(ActorSystem.scala:111)
    play.core.Invoker$$anonfun$1.apply(Invoker.scala:18)
    play.core.Invoker$$anonfun$1.apply(Invoker.scala:17)
    scala.Option.map(Option.scala:145)
    play.core.Invoker$.<init>(Invoker.scala:17)
    play.core.Invoker$.<clinit>(Invoker.scala)
    java.lang.J9VMInternals.initializeImpl(Native Method)
    java.lang.J9VMInternals.initialize(J9VMInternals.java:200)
    play.api.libs.concurrent.Execution$Implicits$.defaultContext$lzycompute(Execution.scala:7)
    play.api.libs.concurrent.Execution$Implicits$.defaultContext(Execution.scala:6)
    play.api.libs.concurrent.Execution$.<init>(Execution.scala:10)
    play.api.libs.concurrent.Execution$.<clinit>(Execution.scala)
    java.lang.J9VMInternals.initializeImpl(Native Method)
    java.lang.J9VMInternals.initialize(J9VMInternals.java:200)
    play.core.server.servlet.Play2GenericServletRequestHandler.handleAction$1(RequestHandler.scala:334)
    play.core.server.servlet.Play2GenericServletRequestHandler.apply(RequestHandler.scala:314)
    play.core.server.servlet.Play2WarServer$$anonfun$handleRequest$2.apply(Play2Server.scala:64)
    play.core.server.servlet.Play2WarServer$$anonfun$handleRequest$2.apply(Play2Server.scala:64)
    scala.Option.map(Option.scala:145)
    play.core.server.servlet.Play2WarServer$.handleRequest(Play2Server.scala:64)
    play.core.server.servlet.GenericPlay2Servlet.service(Play2CommonServlet.scala:36)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
```

**Comment by mountash** [comment]
I thought that may be something with beta version
This is under play-2.1.5 and play2-war-plugin 1.1
In what dependencies play2-war-core-common not found ?

```
[error] play2-war-core-common not found in dependencies!
java.lang.IllegalArgumentException: play2-war-core-common not found in dependencies!
        at com.github.play2war.plugin.Play2WarCommands$$anonfun$1.apply(Play2WarCommands.scala:63)
        at com.github.play2war.plugin.Play2WarCommands$$anonfun$1.apply(Play2WarCommands.scala:55)
        at sbt.Scoped$$anonfun$hf13$1.apply(Structure.scala:589)
        at sbt.Scoped$$anonfun$hf13$1.apply(Structure.scala:589)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
        at sbt.std.Transform$$anon$5.work(System.scala:71)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:238)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by dlecan** [comment]
Still an issue for you ?

**Comment by mountash** [comment]
Yes,
I didn`t try the beta3 and beta4 but when running the war on Tomcat 6 
the issue appeared.
03.02.2014 18:58, Damien Lecan:

> Still an issue for you ?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/dlecan/play2-war-plugin/issues/211#issuecomment-33961858.

## 

С уважением,
Сергей Золотов

**Comment by dlecan** [comment]
I see several issues in your bug report:
- Play2War can't run offline
- `UnsatisfiedLinkError` with Akka on IBM J9 JVM. It's an [Akka issue](https://groups.google.com/forum/#!msg/akka-user/0Z-9_Bmt8p4/Xlg8jsoqvkMJ)

About Play2War that can't be run offline, can you precise the test case ?
Thank you.

**Comment by mountash** [comment]
I downloaded play. Unpacked it. Downloaded play2war-plugin play2-war-core-common 25-servlet jars. Created directory structure in play/repository/local for play2war. 
When running and compiling app under play console everything is fine.
When trying to create war file a message recieved: play2-war-core-common not found in dependencies!

**Comment by dlecan** [comment]
Some SBT/ivy2 metadata must be missing from your manual packaging.
Is it possible for you to let SBT download Play2War from Internet then package the Play repository ?

**Comment by mountash** [comment]
No, unfortunately server has no access to public repositories.
But I found a way out. I packaged Play on another server and then copied the play2war cache to the one, which has no access, and it worked.

**Comment by dlecan** [comment]
Cool.
