### ISSUE TITLE
Classcast Exception with deployment to Glassfish

### ISSUE THREAD

**Issue by joesan** [play2war/play2-war-plugin#214]
I'm deploying the generated war file into Glassfish which results into the following exception:

```
[2014-01-09T10:03:46.946+0100] [glassfish 4.0] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=74 _ThreadName=AutoDeployer] [timeMillis: 1389258226946] [levelValue: 1000] [[
  Exception while deploying the app [server-2.0-SNAPSHOT] : com.sun.proxy.$Proxy169 cannot be cast to javax.servlet.annotation.WebServlet. Related annotation information: annotation [@javax.servlet.annotation.WebServlet(loadOnStartup=-1, initParams=[], smallIcon=, description=, name=Play, value=[], largeIcon=, asyncSupported=true, displayName=, urlPatterns=[/])] on annotated element [class play.core.server.servlet30.Play2Servlet] of type [TYPE]
com.sun.proxy.$Proxy169 cannot be cast to javax.servlet.annotation.WebServlet. Related annotation information: annotation [@javax.servlet.annotation.WebServlet(loadOnStartup=-1, initParams=[], smallIcon=, description=, name=Play, value=[], largeIcon=, asyncSupported=true, displayName=, urlPatterns=[/])] on annotated element [class play.core.server.servlet30.Play2Servlet] of type [TYPE]
    at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:367)
    at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:375)
    at org.glassfish.apf.impl.AnnotationProcessorImpl.processAnnotations(AnnotationProcessorImpl.java:289)
    at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:195)
    at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:134)
    at com.sun.enterprise.deployment.archivist.Archivist.processAnnotations(Archivist.java:626)
    at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:462)
    at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:446)
    at org.glassfish.web.deployment.archivist.WebArchivist.postAnnotationProcess(WebArchivist.java:338)
    at org.glassfish.web.deployment.archivist.WebArchivist.postAnnotationProcess(WebArchivist.java:91)
    at com.sun.enterprise.deployment.archivist.Archivist.readRestDeploymentDescriptors(Archivist.java:420)
    at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:396)
    at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:271)
    at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:280)
    at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:241)
    at com.sun.enterprise.deployment.archivist.ApplicationFactory.openArchive(ApplicationFactory.java:161)
    at org.glassfish.javaee.core.deployment.DolProvider.processDOL(DolProvider.java:198)
    at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:222)
    at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:96)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.loadDeployer(ApplicationLifecycle.java:878)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:818)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:374)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
    at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:537)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:546)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1423)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1500(CommandRunnerImpl.java:108)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1762)
    at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:164)
    at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:595)
    at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:482)
    at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:410)
    at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:401)
    at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:233)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ClassCastException: com.sun.proxy.$Proxy169 cannot be cast to javax.servlet.annotation.WebServlet
    at org.glassfish.web.deployment.annotation.handlers.WebServletHandler.processAnnotation(WebServletHandler.java:84)
    at com.sun.enterprise.deployment.annotation.factory.SJSASFactory$LazyAnnotationHandler.processAnnotation(SJSASFactory.java:148)
    at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:344)
    ... 36 more
]]
```

I'm sure that I'm using Servlet 3.0.1 API as I have the jar file in the lib folder where my domain is runnning. Any clue as to why this would run into this error?

**Comment by joesan** [comment]
Looks like this is the root cause for the issue:

```
[2014-01-09T10:03:46.930+0100] [glassfish 4.0] [SEVERE] [] [global] [tid: _ThreadID=74 _ThreadName=AutoDeployer] [timeMillis: 1389258226930] [levelValue: 1000] [[
  The Class play.core.server.servlet30.Play2Servlet having annotation javax.servlet.annotation.WebListener need to implement one of the following interfaces: javax.servlet.ServletContextLisener, javax.servlet.ServletContextAttributeListener, javax.servlet.ServletRequestListener, javax.servletServletRequestAttributeListener, javax.servlet.http.HttpSessionListener, javax.servlet.http.HttpSessionAttributeListener, javax.servlet.http.HttpSessionIdListener.
 symbol: TYPE location: class play.core.server.servlet30.Play2Servlet

]]
```

**Comment by dlecan** [comment]
As [you have already written](http://www.coderanch.com/t/626627/oa/Error-WebListener-Annotation), `Play2Servlet` annotated with `@WebListener` extends an abstract class which extends itself `HttpServlet` and implements`ServletContextListener`.

Glassfish doesn't seem to be happy with a such hierarchy, I can force "ServletContextListener" implementation in Play2Servlet.
Are you ok this that solution ?

**Comment by joesan** [comment]
Yes can you please add that. I will try to install that in Glassfish and post my findings here.

**Comment by dlecan** [comment]
Someone has a similar issue and has submitted a PR: #217
