### ISSUE TITLE
Perfectly valid Play 2.2.1 appliction does not run on Tomcat 7.

### ISSUE THREAD

**Issue by akuklev** [play2war/play2-war-plugin#221]
Our Play 2.2.1 application (a multi-module one) perfectly starts via play run and play start, however if we make a servlet container for Tomcat7 with play2-war-plugin 1.2-beta4 or beta2 or beta3, it doesn't work at all. Tomcat (7.0.27) says only this:

```
java.lang.ClassCastException: play.api.mvc.Results$Status cannot be cast to scala.concurrent.Future 
    play.core.server.servlet.Play2GenericServletRequestHandler.apply(RequestHandler.scala:323)  
    play.core.server.servlet.Play2WarServer$$anonfun$handleRequest$2.apply(Play2Server.scala:64)
    play.core.server.servlet.Play2WarServer$$anonfun$handleRequest$2.apply(Play2Server.scala:64)
    scala.Option.map(Option.scala:145)
    play.core.server.servlet.Play2WarServer$.handleRequest(Play2Server.scala:64)
    play.core.server.servlet.GenericPlay2Servlet.service(Play2CommonServlet.scala:36)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
```

**Comment by yanns** [comment]
Is it a java or Scala application? Could you provide sample coffee that reproduces this error?

**Comment by akuklev** [comment]
It's a Java application, I'll be able to provide code on monday.

**Comment by dlecan** [comment]
Any code ?

**Comment by szotyi** [comment]
Is this fixed? @kuklev can you give a followup on this?
We have ran into it, with a play 2.1.3 app, using play2war 1.0.2. Here is the log from Tomcat7:

```
java.lang.AbstractMethodError: play.core.server.servlet.WarApplication.get()Lscala/util/Either;
    at play.core.server.Server$class.sendHandler$1(Server.scala:56) ~[play.play_2.10-2.1.3.jar:2.1.3]
    at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:88) ~[play.play_2.10-2.1.3.jar:2.1.3]
    at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:87) ~[play.play_2.10-2.1.3.jar:2.1.3]
    at scala.util.Either$RightProjection.flatMap(Either.scala:523) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at play.core.server.Server$class.getHandlerFor(Server.scala:87) ~[play.play_2.10-2.1.3.jar:2.1.3]
    at play.core.server.servlet.Play2WarServer.getHandlerFor(Play2Server.scala:71) ~[com.github.play2war.play2-war-core-common_2.10-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
    at play.core.server.servlet.Play2GenericServletRequestHandler$$anonfun$9.apply(RequestHandler.scala:134) ~[com.github.play2war.play2-war-core-common_2.10-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
    at play.core.server.servlet.Play2GenericServletRequestHandler$$anonfun$9.apply(RequestHandler.scala:134) ~[com.github.play2war.play2-war-core-common_2.10-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
    at scala.util.Either.fold(Either.scala:98) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at play.core.server.servlet.Play2GenericServletRequestHandler.apply(RequestHandler.scala:128) ~[com.github.play2war.play2-war-core-common_2.10-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
    at play.core.server.servlet.Play2WarServer$$anonfun$handleRequest$2.apply(Play2Server.scala:64) ~[com.github.play2war.play2-war-core-common_2.10-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
    at play.core.server.servlet.Play2WarServer$$anonfun$handleRequest$2.apply(Play2Server.scala:64) ~[com.github.play2war.play2-war-core-common_2.10-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
    at scala.Option.map(Option.scala:145) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at play.core.server.servlet.Play2WarServer$.handleRequest(Play2Server.scala:64) ~[com.github.play2war.play2-war-core-common_2.10-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
    at play.core.server.servlet.GenericPlay2Servlet.service(Play2CommonServlet.scala:36) ~[com.github.play2war.play2-war-core-common_2.10-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722) ~[tomcat-servlet-api-3.0.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) ~[tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) ~[tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224) ~[tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169) ~[tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) ~[tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) ~[tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) ~[tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927) ~[tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) ~[tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) ~[tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987) ~[tomcat-coyote-7.0.26.jar:7.0.26]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579) ~[tomcat-coyote-7.0.26.jar:7.0.26]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309) ~[tomcat-coyote-7.0.26.jar:7.0.26]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146) ~[na:1.6.0_30]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.6.0_30]
    at java.lang.Thread.run(Thread.java:701) ~[na:1.6.0_30]
```

I created a small multi module project and it happens. It is the default play app with a test module just echoing a string. You can check out the project here: https://github.com/szotyi/play-module-test It has a vagrant box (in devbox), that starts up a virtual machine with tomcat7 installed.

If you need more info, I would be happy to provide them.

**Comment by akuklev** [comment]
@szotyi The problem is still there urging for a fix. I'm working on another project currently, so I just forgot to prepare and send the code.

**Comment by dlecan** [comment]
@szotyi why do you say it's the same issue ? I see an AbstractError instead of a classcast exception.
Play 2.1.3 and Play2War 1.0.2-snapshot are quite old now, can you try with Play 2.1.5 and Play2war 1.1.1 ?

**Comment by szotyi** [comment]
@dlecan thx for reply, I will try it with 2.1.5/1.1.1 combo next week and get back with results. If it's not working, should I start a new issue or can I just comment here? I assumed it could be the same problem, because it's Tomcat7 and multi module project also.

**Comment by szotyi** [comment]
Hi, I tried with 2.1.5/1.1.1 combo, than I tried with 2.2.2/1.2.beta combo and the deploy went fine. Thanks for the help.
