### ISSUE TITLE
ERROR deploy with tomcat  7 

### ISSUE THREAD

**Issue by kwanchanok-wc** [play2war/play2-war-plugin#227]
i deploy in tomcat 7 and error 404 
and i look in log file found this error
Error this : 

```
java.lang.ClassNotFoundException: play.core.server.servlet25.Play2Servlet
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
    at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:527)
    at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:509)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:137)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4854)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1113)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1671)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
```

build.scala

``` scala
import sbt._
import Keys._
import play.Project._
import com.github.play2war.plugin._

object ApplicationBuild extends Build {

    val appName         = "AuditApp"
    val appVersion      = "1.0-SNAPSHOT"
    val apache_poi = "org.apache.poi" % "poi-ooxml" % "3.8"
    val apache = "org.apache.poi" % "poi" % "3.8"
    val appDependencies = Seq(
      javaCore,
      javaJdbc,
      javaEbean,
      apache_poi,
      apache,
      "com.google.code.gson" % "gson" % "2.2.4",
      "org.json"%"org.json"%"chargebee-1.0",
      "com.github.play2war.ext" %% "redirect-playlogger" % "1.0.1"
    )

    val main = play.Project(appName, appVersion, appDependencies)
    .settings(Play2WarPlugin.play2WarSettings: _*)
    .settings(
      Play2WarKeys.servletVersion := "3.0",
      javacOptions in Compile ++= Seq("-source", "1.6", "-target", "1.6"),
      resolvers += "snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
    )

}       
```

**Comment by dlecan** [comment]
Which Play version ?
Which Play2War version ?
What is the content of `<WAR_FILE>!/WEB-INF/lib` ?

**Comment by kwanchanok-wc** [comment]
Play version - 2.2.2-RC2
Play2War version 1.2-beta4
What is the content of <WAR_FILE>!/WEB-INF/lib ==> has jar file

note =>i can deploy on tomcat6

**Comment by kwanchanok-wc** [comment]
I can solved it already. ^^ 
I remove web.xml in folder WEB-INF and my web application can use

**Comment by dlecan** [comment]
You're right, you shouldn't have a `web.xml` file with servlet 3.0 container configuration.
