### ISSUE TITLE
support for wildfly 8

### ISSUE THREAD

**Issue by bharath12345** [play2war/play2-war-plugin#228]

**Comment by bharath12345** [comment]
I can contribute for Wildfly8 support. Not new to scala or play but new to sbt plugin dev. Presently reading your code.

**Comment by dlecan** [comment]
Is it presently working with Wildfly ?
If not, any issues to raise ?

**Comment by bharath12345** [comment]
I created the basic Scala app with "play new". On deploying the WAR in Wildfly I get the exceptions pasted below. The version info -

Play - v2.2.1
Play2War plugin - 1.2-beta4
Wildfly - 8.0 Final

Exceptions - (my app name is _fordoc_)

```
[0m[0m17:45:00,574 INFO  [org.jboss.weld.deployer] (MSC service thread 1-6) JBAS016008: Starting weld service for deployment fordoc-1.0-SNAPSHOT.war
[0m[31m17:45:03,552 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-5) MSC000001: Failed to start service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".WeldStartService: Failed to start service
at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904) [jboss-msc-1.2.0.Final.jar:1.2.0.Final]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_51]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_51]
at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_51]
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type Set<Service> with qualifiers @Default
at injection point [BackedAnnotatedParameter] Parameter 1 of [BackedAnnotatedConstructor] @Inject com.google.common.util.concurrent.ServiceManager(Set<Service>)
at com.google.common.util.concurrent.ServiceManager.<init>(ServiceManager.java:0)  
at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:368)
at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:289)
at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:135)
at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:166)
at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:514)
at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:60)
at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:53)
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_51]
... 3 more
```

This is followed by some more info -

```
[0m[0m17:45:05,308 INFO  [org.jboss.as.controller] (DeploymentScanner-threads - 2) JBAS014774: Service status report
JBAS014775:    New missing/unsatisfied dependencies:
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".WeldBootstrapService (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".WeldInstantiator, service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.faces.webapp.FacetTag".WeldInstantiator, service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.Play2Servlet".WeldInstantiator, service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".UndertowDeploymentInfoService, JBAS014799: ... and 6 more ] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".WeldStartService (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.faces.webapp.FacetTag".WeldInstantiator, service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.Play2Servlet".WeldInstantiator, service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".WeldInstantiator, service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldTerminalListener".WeldInstantiator] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".CREATE (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".START] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT", service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".deploymentCompleteService] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".START] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.faces.webapp.FacetTag".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT", service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".deploymentCompleteService] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".CREATE (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT", service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".deploymentCompleteService] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".CREATE (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT", service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".deploymentCompleteService] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".CREATE (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".START] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT", service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".deploymentCompleteService] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".START] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldTerminalListener".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT", service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".deploymentCompleteService] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.AsyncListener".CREATE (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.AsyncListener".START] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.AsyncListener".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT", service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".deploymentCompleteService] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.AsyncListener".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.AsyncListener".START] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.Play2Servlet".CREATE (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.Play2Servlet".START] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.Play2Servlet".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT", service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".deploymentCompleteService] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.Play2Servlet".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.Play2Servlet".START] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".ee.ComponentRegistry (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".UndertowDeploymentInfoService] 
  service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".jndiDependencyService (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".START, service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.Play2Servlet".START, service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START, service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".component."play.core.server.servlet30.AsyncListener".START, JBAS014799: ... and 3 more ] 
  service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT" (missing) dependents: [service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".deploymentCompleteService] 
  service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".UndertowDeploymentInfoService (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT"] 
  service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".codec (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/fordoc-1.0-SNAPSHOT".UndertowDeploymentInfoService] 
JBAS014777:   Services which failed to start:      service jboss.deployment.unit."fordoc-1.0-SNAPSHOT.war".WeldStartService
```

Please note -
- I am running Willfly in standalone-full deployment mode
- While building the WAR I got the following **Warning** on my sbt console - 
  [warn] Unknown servlet container version: 3.1. Force default 3.0 version

**Comment by bharath12345** [comment]
Looks like the @Inject annotation is causing the problem which comes from Google Guava lib packaged in the WAR's WEB-INF/lib

**Comment by dlecan** [comment]
As usual for JBoss, you should isolate the WAR classloader. Play runtime must use WEB-INF/lib jars first (then delegate to parent's classloader).

Look at https://docs.jboss.org/author/display/WFLY8/Class+Loading+in+WildFly I think.

**Comment by bharath12345** [comment]
Sorry, my bad. The problem got fixed after I followed your advise. Here is what I did -
- created a new slot in JBoss for Guava 14.0.1
- added a jboss-deployment-structure.xml to use this slot of guava
- excluded guava from getting packaged by Play2War

My Play2 UI shows up absolutely clean on Wildfly :-). Thank you!

**Comment by ghost** [comment]
bharath,  Can u please explain how u did those things?
I'm new to wildfly, and i have no knowledge on Guava.

**Comment by bharath12345** [comment]
I wrote whatever little I did on my blog - http://bharathwrites.in/posts/play2-on-jboss-wildfly/

**Comment by dlecan** [comment]
> I wrote whatever little I did on my blog - http://bharathwrites.in/posts/play2-on-jboss-wildfly/

What a great job !
You don't really say why you absolutely need to host your Play applications in Wildfly, do you ?

**Comment by bharath12345** [comment]
Mainly because of Scala and speed of development. However this was an experiment to convince folks to adapt... and for one set of UIs in the larger webapp of my product. But the decision is still pending :)
