### ISSUE TITLE
Error play war

### ISSUE THREAD

**Issue by tru3d3v** [play2war/play2-war-plugin#237]
Hi dlecan,

i have an error when play war, the error message is:

```
[warn] Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/i
vy-releases/com.github.play2war/play2-war-plugin/scala_2.10/sbt_0.13/v1.2-beta4/
ivys/ivy.xml
[warn] Host repo.scala-sbt.org not found. url=http://repo.scala-sbt.org/scalasbt
/sbt-plugin-releases/com.github.play2war/play2-war-plugin/scala_2.10/sbt_0.13/v1
.2-beta4/ivys/ivy.xml
[warn] Host repo1.maven.org not found. url=http://repo1.maven.org/maven2/com/git
hub/play2war/play2-war-plugin_2.10_0.13/v1.2-beta4/play2-war-plugin-v1.2-beta4.p
om
[warn] Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/r
eleases/com/github/play2war/play2-war-plugin_2.10_0.13/v1.2-beta4/play2-war-plug
in-v1.2-beta4.pom
[warn]  module not found: com.github.play2war#play2-war-plugin;v1.2-beta4
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play
2-war-plugin/scala_2.10/sbt_0.13/v1.2-beta4/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.play2
war/play2-war-plugin/scala_2.10/sbt_0.13/v1.2-beta4/ivys/ivy.xml
[warn] ==== local: tried
[warn]   D:\Java\play-2.2.2\repository\local\com.github.play2war\play2-war-plugi
n\scala_2.10\sbt_0.13\v1.2-beta4\ivys\ivy.xml
[warn] ==== Maven2 Local: tried
[warn]   file:/C:/Users/Muchlis/.m2/repository/com/github/play2war/play2-war-plu
gin_2.10_0.13/v1.2-beta4/play2-war-plugin-v1.2-beta4.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.10
_0.13/v1.2-beta4/play2-war-plugin-v1.2-beta4.pom
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-wa
r-plugin_2.10_0.13/v1.2-beta4/play2-war-plugin-v1.2-beta4.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.play2war#play2-war-plugin;v1.2-beta4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that th
ese dependencies exist with the requested attributes.
[warn]          com.github.play2war:play2-war-plugin:v1.2-beta4 (sbtVersion=0.13
, scalaVersion=2.10)
[warn]
sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-plugi
n;v1.2-beta4: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:213)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:104)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:51)
        at sbt.IvySbt$$anon$3.call(Ivy.scala:60)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRet
ries$1(Locks.scala:81)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:
102)
        at xsbt.boot.Using$.withResource(Using.scala:11)
        at xsbt.boot.Using$.apply(Using.scala:10)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:60)
        at sbt.IvySbt.withIvy(Ivy.scala:101)
        at sbt.IvySbt.withIvy(Ivy.scala:97)
        at sbt.IvySbt$Module.withModule(Ivy.scala:116)
        at sbt.IvyActions$.update(IvyActions.scala:121)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala
:1144)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala
:1142)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$73.apply(Defaults.scala:1
165)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$73.apply(Defaults.scala:1
163)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1167)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1162)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1170)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1135)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1113)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:23
7)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:23
7)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
tions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.github.play2
```

Advice me please.

Best Regards

Muchlis

**Comment by yanns** [comment]
Same problem as here: https://github.com/dlecan/play2-war-plugin/issues/225 ?

**Comment by dlecan** [comment]
Wrong version : `v1.2-beta4` instead of `1.2-beta4` (notice `v`).

**Comment by tru3d3v** [comment]
plugins.sbt

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.2.2")
addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.2-beta4")

is it right?

**Comment by tru3d3v** [comment]
[error] References to undefined settings:
[error]
[error]   *:servletVersion from *:war
[error]
[error]   *:servletVersion from *:war
[error]
[error]   *:servletVersion from *:libraryDependencies
[error]
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by dlecan** [comment]
Can you provide more project's configuration ? `Build.scala`, `plugins.sbt`

**Comment by tru3d3v** [comment]
## build.sbt 

``` scala
import com.github.play2war.plugin._


    name := "SasmitaERP"

    version := "1.0-SNAPSHOT"

    libraryDependencies ++= Seq(
      javaJdbc,
      javaEbean,
      cache
    )     

    play.Project.playJavaSettings

    Play2WarPlugin.play2WarSettings
```

---

plugins.sbt

``` scala
// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.2.2")

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.2-beta4")
```

**Comment by dlecan** [comment]
Play 2.2.x and Play2War 1.2.x are compatible with SBT 0.13.
It will be possible to use SBT 0.13 with Play 2.3.x and Play2War 1.3.x
