### ISSUE TITLE
Webapp redeployment error

### ISSUE THREAD

**Issue by khkarens** [play2war/play2-war-plugin#238]
Hello, 

We are facing a sever exception during the redeployment of a simple play war project on Apache Tomcat 7.0.52 server. Bellow is the content of localhost.2014.04.02.log file:

```
Apr 2, 2014 3:59:04 PM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > contextInitialized
Apr 2, 2014 3:59:08 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: contextInitialized()
Apr 2, 2014 3:59:08 PM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: contextInitialized()
Apr 2, 2014 3:59:08 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: attributeAdded('org.apache.jasper.compiler.TldLocationsCache', 'org.apache.jasper.compiler.TldLocationsCache@dec87')
Apr 2, 2014 4:00:18 PM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > contextDestroyed
Apr 2, 2014 4:00:18 PM org.apache.catalina.core.StandardContext listenerStop
SEVERE: Exception sending context destroyed event to listener instance of class play.core.server.servlet30.Play2Servlet
java.lang.NoClassDefFoundError: play/core/server/servlet/Play2WarServer$$anonfun$stop$1
    at play.core.server.servlet.Play2WarServer$.stop(Play2Server.scala:56)
    at play.core.server.servlet.GenericPlay2Servlet.contextDestroyed(Play2CommonServlet.scala:51)
    at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5002)
    at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5647)
    at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
    at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:1028)
    at org.apache.catalina.startup.HostConfig.undeploy(HostConfig.java:1479)
    at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1407)
    at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1627)
    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:329)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
    at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1374)
    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1530)
    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1519)
    at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.ClassNotFoundException: play.core.server.servlet.Play2WarServer$$anonfun$stop$1
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
    at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
    ... 17 more
Apr 2, 2014 4:00:25 PM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > contextInitialized
```

Please, let me know if you need any more info. 

Thanks,
Karen

**Comment by yanns** [comment]
does it happen by every redeployment?
How do you trigger the redeployment?

**Comment by ShushanArakelyan** [comment]
Hi All,

I'm facing a similar problem, and in my case it happens during every redeployment.
I'm doing 

> touch webapps/my_webapp.war 
> then I find this error in the log.

Thank you, 
Shushan

**Comment by khkarens** [comment]
Hi Yanns, 

Yes, it happens by every redeployment. Either when I "touch" or replace the war package.

thanks,
Karen

**Comment by dlecan** [comment]
Play runtime is not designed to be embedded in another classloader.
By luck/accident, it is compatible with a one-time-deployment model and only in "prod" mode. Hot redeployment is not supported.

Play2War shouldn't be used during development.

**Comment by khkarens** [comment]
Thank you Damien, but could you, please, clarify what you mean by: "Play2War shouldn't be used during development" ?

I can't understand why should one generate a .war package from a play project if one can't deploy that package to a web server (Tomcat etc.)?

**Comment by dlecan** [comment]
> clarify what you mean by: "Play2War shouldn't be used during development" ?

WAR package provided by Play2War is a solution for operationals, who require every Java web application must be deployed in an application server.

So developers don't require Play2war.

"war" and "dist" are similar: to package for production.
