### ISSUE TITLE
Unable to resolve reference "NonJtaDataSourceWrapper" JPA with Websphere

### ISSUE THREAD

**Issue by poornerd** [play2war/play2-war-plugin#240]
I am trying to deploy a WAR file for the first time to Websphere (newest Community Version), and keep getting this error: Unable to resolve reference "NonJtaDataSourceWrapper"

**The WAR worked fine on Tomcat 7.0.5x**

My persistence.xml looks like this:

```
    <persistence-unit name="uatAgribankOraclePersistenceUnit" transaction-type="RESOURCE_LOCAL">
        <provider>org.hibernate.ejb.HibernatePersistence</provider>
        <non-jta-data-source>UatAgribankOracleDS</non-jta-data-source>
        <properties>
            <property name="hibernate.dialect" value="org.hibernate.dialect.Oracle10gDialect"/>
            <property name="hibernate.hbm2ddl.auto" value="validate"/>
            <property name="hibernate.show_sql" value="false"/>
            <property name="hibernate.format_sql" value="false"/>
            <property name="hibernate.use_sql_comments" value="false"/>
            <property name="hibernate.globally_quoted_identifiers" value="false"/>
        </properties>
    </persistence-unit>
```

I also created a datasource on the Websphere, and added it like this to the persistence.xml:

```
<non-jta-data-source>java:/UatAgribankOracleDS</non-jta-data-source>
```

and pretty much got the same error.

Does anyone have experience with this? Any ideas?

Here is part of the stack trace:

```
Unable to resolve reference "NonJtaDataSourceWrapper"
    in gbean default/ROOT/1397127084270/war?J2EEApplication=null,PersistenceUnitModule=WEB-INF/lib/default.api-1.0-SNAPSHOT.jar,WebModule=default/ROOT/1397127084270/war,j2eeType=PersistenceUnit,name=uatEnterprisePersistenceUnit
    to a gbean matching the pattern [?name=UatEnterpriseDS#org.apache.geronimo.naming.ResourceSource]
    due to: No matches for referencePatterns: [?name=UatEnterpriseDS#org.apache.geronimo.naming.ResourceSource] (no matches)
Unable to resolve reference "NonJtaDataSourceWrapper"
    in gbean default/ROOT/1397127084270/war?J2EEApplication=null,PersistenceUnitModule=WEB-INF/lib/default.api-1.0-SNAPSHOT.jar,WebModule=default/ROOT/1397127084270/war,j2eeType=PersistenceUnit,name=uatAgribankOraclePersistenceUnit
    to a gbean matching the pattern [?name=UatAgribankOracleDS#org.apache.geronimo.naming.ResourceSource]
    due to: No matches for referencePatterns: [?name=UatAgribankOracleDS#org.apache.geronimo.naming.ResourceSource] (no matches)
    at org.apache.geronimo.deployment.DeploymentContext.getConfigurationData(DeploymentContext.java:550)
    at org.apache.geronimo.deployment.Deployer.install(Deployer.java:355)
    at org.apache.geronimo.deployment.Deployer.deploy(Deployer.java:272)
    at org.apache.geronimo.deployment.Deployer.deploy(Deployer.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.geronimo.gbean.runtime.ReflectionMethodInvoker.invoke(ReflectionMethodInvoker.java:34)
    at org.apache.geronimo.gbean.runtime.GBeanOperation.invoke(GBeanOperation.java:131)
    at org.apache.geronimo.gbean.runtime.GBeanInstance.invoke(GBeanInstance.java:883)
    at org.apache.geronimo.kernel.basic.BasicKernel.invoke(BasicKernel.java:245)
    at org.apache.geronimo.deployment.plugin.local.AbstractDeployCommand.doDeploy(AbstractDeployCommand.java:116)
    at org.apache.geronimo.deployment.plugin.local.DistributeCommand.run(DistributeCommand.java:61)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by poornerd** [comment]
To resolve this I added a datasource to the Websphere Application Server.  Then I added this to the geronimo-web.xml in the WAR file:

```
        <dep:dependencies>
            <dep:dependency>
                <dep:groupId>console.dbpool</dep:groupId>
                <dep:artifactId>MyDS</dep:artifactId>
                <dep:version>1.0</dep:version>
                <dep:type>car</dep:type>
            </dep:dependency>
            <dep:dependency>
                <dep:groupId>com.oracle</dep:groupId>
                <dep:artifactId>ojdbc6</dep:artifactId>
                <dep:version>11.2.0.3</dep:version>
                <dep:type>jar</dep:type>
            </dep:dependency>
        </dep:dependencies>
```

and

```
    <nam:resource-ref xmlns:nam="http://geronimo.apache.org/xml/ns/naming-1.2">
        <nam:ref-name>jdbc/MyDataSource</nam:ref-name>
        <nam:pattern>
            <nam:groupId>console.dbpool</nam:groupId>
            <nam:artifactId>MyDS</nam:artifactId>
            <nam:version>1.0</nam:version>
            <nam:name>MyDS</nam:name>
        </nam:pattern>
    </nam:resource-ref>
```

**Comment by dlecan** [comment]
Thank you @poornerd
