### ISSUE TITLE
play2war error resolving dependency

### ISSUE THREAD

**Issue by lburcha** [play2war/play2-war-plugin#251]
I am currently using play 2.2.3 after running play in my project folder I am confronted with this error. Is there anyway to fix this so I can get my App up and running?

java.lang.AbstractMethodError
        at play.PlayInternalKeys$class.$init$(PlayInternalKeys.scala:20)
        at com.github.play2war.plugin.Play2WarPlugin$.<init>(Play2WarPlugin.scala:21)
        at com.github.play2war.plugin.Play2WarPlugin$.<clinit>(Play2WarPlugin.scala)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:340)
        at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:13)
        at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:19)
        at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:22)
        at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:22)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream$$anonfun$$plus$plus$1.apply(Stream.scala:330)
        at scala.collection.immutable.Stream$$anonfun$$plus$plus$1.apply(Stream.scala:330)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream$$anonfun$$plus$plus$1.apply(Stream.scala:330)
        at scala.collection.immutable.Stream$$anonfun$$plus$plus$1.apply(Stream.scala:330)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream.force(Stream.scala:249)
        at scala.collection.immutable.Stream.mkString(Stream.scala:702)
        at sbt.BuildUtil$.importNames(BuildUtil.scala:87)
        at sbt.BuildUtil$.importAll(BuildUtil.scala:92)
        at sbt.BuildUtil$.importAllRoot(BuildUtil.scala:93)
        at sbt.BuildUtil$.getImports(BuildUtil.scala:84)
        at sbt.DetectedPlugins.imports$lzycompute(BuildStructure.scala:103)
        at sbt.DetectedPlugins.imports(BuildStructure.scala:103)
        at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:507)
        at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:502)
        at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:501)
        at scala.Option.getOrElse(Option.scala:120)
        at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:501)
        at sbt.Load$$anonfun$loadSettings$1$2.apply(Load.scala:500)
        at sbt.Load$$anonfun$loadSettings$1$2.apply(Load.scala:500)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Load$.loadSettings$1(Load.scala:500)
        at sbt.Load$.sbt$Load$$expand$1(Load.scala:523)
        at sbt.Load$.loadSettings(Load.scala:528)
        at sbt.Load$.sbt$Load$$loadSbtFiles$1(Load.scala:464)
        at sbt.Load$.defaultLoad$1(Load.scala:475)
        at sbt.Load$.loadTransitive(Load.scala:478)
        at sbt.Load$.loadProjects$1(Load.scala:418)
        at sbt.Load$.loadUnit(Load.scala:419)
        at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:256)
        at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:256)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:93)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:92)
        at sbt.BuildLoader.apply(BuildLoader.scala:143)
        at sbt.Load$.loadAll(Load.scala:312)
        at sbt.Load$.loadURI(Load.scala:264)
        at sbt.Load$.load(Load.scala:260)
        at sbt.Load$.load(Load.scala:251)
        at sbt.Load$.apply(Load.scala:134)
        at sbt.Load$.defaultLoad(Load.scala:37)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:473)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
        at sbt.Command$.process(Command.scala:95)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
        at sbt.State$$anon$1.process(State.scala:179)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.MainLoop$.next(MainLoop.scala:100)
        at sbt.MainLoop$.run(MainLoop.scala:93)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
        at sbt.Using.apply(Using.scala:25)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
        at sbt.MainLoop$.runLogged(MainLoop.scala:25)
        at sbt.StandardMain$.runManaged(Main.scala:57)
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.AbstractMethodError
[error] Use 'last' for the full log.

**Comment by quistj** [comment]
How did you resolve this issue?

**Comment by VitalyOlegovic** [comment]
To solve this issue, you have to update the plugin version:

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.3-beta2")

1.3-beta2 is the correct version.
