### ISSUE TITLE
Play 2.3.1 deploy problems on jboss 7.1.1

### ISSUE THREAD

**Issue by diogocarleto** [play2war/play2-war-plugin#256]
Hello, I'm trying to deploy a simple play-scala(https://github.com/playframework/playframework/tree/master/templates/play-scala) project on jboss 7.1.1 and I've got the following error:

<pre>
06:38:55,567 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-9) JBAS015876: Starting deployment of "play-scala-1.0.war"
06:38:58,890 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) JBAS010403: Deploying JDBC-compliant driver class org.h2.Driver (version 1.3)
06:38:58,954 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/play-scala-1.0]] (MSC service thread 1-1) PlayServletWrapper > contextInitialized
06:38:59,074 INFO  [stdout] (MSC service thread 1-1) Play logs now directly handled by this application server
06:38:59,128 INFO  [play] (MSC service thread 1-1) Force Play 'application.context' to '/play-scala-1.0/'
06:38:59,362 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/play-scala-1.0]] (MSC service thread 1-1) Exception sending context initialized event to listener instance of class play.core.server.servlet30.Play2Servlet: java.lang.IllegalArgumentException: Cannot check isDirectory for a URL with protocol='vfs'
    at play.utils.Resources$.isDirectory(Resources.scala:18) [com.typesafe.play.play_2.11-2.3.1.jar:2.3.1]
    at play.api.i18n.DefaultMessagesPlugin$$anonfun$loadMessages$1.apply(Messages.scala:351) [com.typesafe.play.play_2.11-2.3.1.jar:2.3.1]
    at play.api.i18n.DefaultMessagesPlugin$$anonfun$loadMessages$1.apply(Messages.scala:351) [com.typesafe.play.play_2.11-2.3.1.jar:2.3.1]
    at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259) [org.scala-lang.scala-library-2.11.1.jar:]
    at scala.collection.immutable.List.foreach(List.scala:383) [org.scala-lang.scala-library-2.11.1.jar:]
    at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258) [org.scala-lang.scala-library-2.11.1.jar:]
    at scala.collection.TraversableLike$class.filterNot(TraversableLike.scala:278) [org.scala-lang.scala-library-2.11.1.jar:]
    at scala.collection.AbstractTraversable.filterNot(Traversable.scala:104) [org.scala-lang.scala-library-2.11.1.jar:]
    at play.api.i18n.DefaultMessagesPlugin.loadMessages(Messages.scala:351) [com.typesafe.play.play_2.11-2.3.1.jar:2.3.1]
    at play.api.i18n.DefaultMessagesPlugin.messages(Messages.scala:361) [com.typesafe.play.play_2.11-2.3.1.jar:2.3.1]
    at play.api.i18n.DefaultMessagesPlugin.api$lzycompute(Messages.scala:376) [com.typesafe.play.play_2.11-2.3.1.jar:2.3.1]
    at play.api.i18n.DefaultMessagesPlugin.api(Messages.scala:376) [com.typesafe.play.play_2.11-2.3.1.jar:2.3.1]
    at play.api.i18n.DefaultMessagesPlugin.onStart(Messages.scala:381) [com.typesafe.play.play_2.11-2.3.1.jar:2.3.1]
    at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) [com.typesafe.play.play_2.11-2.3.1.jar:1.0.1]
    at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) [com.typesafe.play.play_2.11-2.3.1.jar:1.0.1]
    at scala.collection.immutable.List.foreach(List.scala:383) [org.scala-lang.scala-library-2.11.1.jar:]
    at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) [com.typesafe.play.play_2.11-2.3.1.jar:1.0.1]
    at play.api.Play$$anonfun$start$1.apply(Play.scala:91) [com.typesafe.play.play_2.11-2.3.1.jar:1.0.1]
    at play.api.Play$$anonfun$start$1.apply(Play.scala:91) [com.typesafe.play.play_2.11-2.3.1.jar:1.0.1]
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [com.typesafe.play.play_2.11-2.3.1.jar:2.3.1]
    at play.api.Play$.start(Play.scala:90) [com.typesafe.play.play_2.11-2.3.1.jar:1.0.1]
    at play.core.server.servlet.WarApplication.<init>(Play2Server.scala:112) [com.github.play2war.play2-war-core-common_2.11-1.3-beta1.jar:1.3-beta1]
    at play.core.server.servlet.Play2WarServer$.apply(Play2Server.scala:43) [com.github.play2war.play2-war-core-common_2.11-1.3-beta1.jar:1.3-beta1]
    at play.core.server.servlet.GenericPlay2Servlet.contextInitialized(GenericPlay2Servlet.scala:45) [com.github.play2war.play2-war-core-common_2.11-1.3-beta1.jar:1.3-beta1]
    at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3392) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContext.start(StandardContext.java:3850) [jbossweb-7.0.13.Final.jar:]
    at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_60]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_60]

06:38:59,418 ERROR [org.apache.catalina.core.StandardContext] (MSC service thread 1-1) Error listenerStart
06:38:59,419 ERROR [org.apache.catalina.core.StandardContext] (MSC service thread 1-1) Context [/play-scala-1.0] startup failed due to previous errors
06:38:59,435 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/play-scala-1.0]] (MSC service thread 1-1) PlayServletWrapper > contextDestroyed
06:38:59,436 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/play-scala-1.0]] (MSC service thread 1-1) Play server stopped
06:38:59,442 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC00001: Failed to start service jboss.web.deployment.default-host."/play-scala-1.0": org.jboss.msc.service.StartException in service jboss.web.deployment.default-host."/play-scala-1.0": JBAS018040: Failed to start context
    at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:95)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_60]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_60]

06:38:59,649 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) JBAS015870: Deploy of deployment "play-scala-1.0.war" was rolled back with failure message {"JBAS014671: Failed services" => {"jboss.web.deployment.default-host.\"/play-scala-1.0\"" => "org.jboss.msc.service.StartException in service jboss.web.deployment.default-host.\"/play-scala-1.0\": JBAS018040: Failed to start context"}}
06:38:59,699 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-4) JBAS015877: Stopped deployment play-scala-1.0.war in 49ms
06:38:59,701 INFO  [org.jboss.as.controller] (DeploymentScanner-threads - 2) JBAS014774: Service status report
JBAS014777:   Services which failed to start:      service jboss.web.deployment.default-host."/play-scala-1.0": org.jboss.msc.service.StartException in service jboss.web.deployment.default-host."/play-scala-1.0": JBAS018040: Failed to start context
</pre>

Should I use the Play 2.2.x?
Thanks

**Comment by gilbertw1** [comment]
I've been having this exact same issue. It looks like the Play Framework can't properly work with the JBoss VFS (virtual file system) urls. I have pretty much no experience with JBoss apart from my research into running a play app on it (version 7.1.1) over the past few hours, and I have been unable to find any satisfying solution.

The only stop gap (read soul crushing) solution I could come up with was to fork the Play Framework (!!!) and add support for VFS where it attempts to load resources. The fork [can be found here](https://github.com/gilbertw1/playframework/tree/2.3.x).

Additionally I've set up an ivy repo on github to host this version of play based off of 2.3-SNAPSHOT and only compiled for scala 2.10. You can try it in your project by doing the following:

In plugins.sbt

```
resolvers += Resolver.url("JBOSS VFS Play Repo", url("https://raw.github.com/gilbertw1/play2-jboss-vfs-repo/master/repo"))(Resolver.ivyStylePatterns)
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3-SNAPSHOT")
```

I don't see any good solution to this problem outside of sending a pull request to the PlayFramework to see if they'll add VFS support directly into Play itself. I don't know that it can be solved via a plugin or not. If anyone has any ideas or a better solution please let me know.

**Comment by yanns** [comment]
I tried to solve this issue as well, and found out that the current play code cannot run with the JBoss VFS.
I tried several configurations, for example with an exploded WAR and other configuration parameters to try to by-pass the JBoss VFS but without any success.

One possible solution would be to find some Java IO Code that JBoss can understand directly without VFS, and to patch Play to use this code instead of the existing one.

Another solution would be to factorize all IO Code from Play into one project, and to overwrite this jar with a jar using the VFS from JBoss.

**Comment by dlecan** [comment]
Did you try this configuration: https://github.com/play2war/play2-war-plugin/wiki/Configurationspecialebeanjboss7 ?

**Comment by gilbertw1** [comment]
I did, that was one of the first things I tried after finding a similar issue that recommended it as a solution. I've found that the problem really stems from these two spots:

[Resources.scala:15](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/utils/Resources.scala#L15)
[PlayIO.scala:55](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/utils/PlayIO.scala#L55)

After updating this two locations to do the correct thing when they encountered a vfs url I was able to get everything working correctly.

**Comment by yanns** [comment]
There was some activity in play to support OSGI bundles:
https://github.com/playframework/playframework/commit/9f212ff8ce158d6792d2fdbab6e2a591b2b46ef5

@gilbertw1 maybe you can push your modifications to Play?

**Comment by JonnyHeavey** [comment]
@gilbertw1 Has a pull request been made to Play? I think these changes would be extremely beneficial.

**Comment by dlecan** [comment]
Close, as it's a Play 2 limitation.

**Comment by davidt99** [comment]
Hi,
@gilbertw1 , I tried to find your commits in [the repository](https://github.com/gilbertw1/playframework/tree/2.3.x), but i couldn't.
I want to apply this patch to the new version of play.
Can you show me the specific changes?

**Comment by gilbertw1** [comment]
Hey @davidt99, I was able to track down the commit.....you can find it here:

https://github.com/gilbertw1/playframework/commit/9f9618d52ea54308418d08d29d711c5855c1d3b1

**Comment by sauldhernandez** [comment]
Has @gilbertw1's commit  been integrated into the Play2 repository? Was trying to run a play application on Wildfly 8 with no success.

**Comment by gilbertw1** [comment]
@sauldhernandez: the guys at playframework made it clear that they weren't going to merge any commits that included third party libs from JBoss. So it looks like your only choice is to probably patch Play with these changes if you want to use JBoss.
