### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class play.core.server.servlet.Play2WarServer$

### ISSUE THREAD

**Issue by srivatsan-sridharan** [play2war/play2-war-plugin#274]
Deployment on Tomcat version 7 was successful. However, we are getting the below exception while trying to deploy helloworld application on GAE.

Target servlet version 2.5. PlayFramework 2.3.5, Play2WarPlugin 1.3-beta2, appenginesdk-java-1.9.7 are being used.

Exception Stack Trace

```
Uncaught exception from servlet
java.lang.NoClassDefFoundError: Could not initialize class play.core.server.servlet.Play2WarServer$
    at play.core.server.servlet.GenericPlay2Servlet.contextInitialized(GenericPlay2Servlet.scala:45)
    at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:548)
    at org.mortbay.jetty.servlet.Context.startContext(Context.java:136)
    at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
    at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
    at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.createHandler(AppVersionHandlerMap.java:199)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.getHandler(AppVersionHandlerMap.java:174)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:480)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:438)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:445)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:220)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:309)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:301)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:442)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
    at java.lang.Thread.run(Thread.java:724)
```

**Comment by dlecan** [comment]
Play2War and Play2 are not compatible with GAE as-is.
Some work is necessary, at least because Akka thread model is incompatible with GAE's one.

Your exception is an example of another compatibility issue. Something wrong happens in [Play2WarServer constructor](https://github.com/play2war/play2-war-plugin/blob/develop/project-code/core/common/src/main/scala/play/core/server/servlet/GenericPlay2Servlet.scala#L45), but we don't know what because real exception is lost in your logs.

**Comment by dlecan** [comment]
Feel free to reopen this issue if you have more information to give us.
