### ISSUE TITLE
AbstractMethodError Error

### ISSUE THREAD

**Issue by kirankumarhm** [play2war/play2-war-plugin#288]
# I am using windows 7 + JDK 1.7 + Play 1.3.3
# my build.sbt configuration is 

import com.github.play2war.plugin._

name := "play-java-spring"

version := "1.0-SNAPSHOT"

Play2WarPlugin.play2WarSettings

Play2WarKeys.servletVersion := "3.0"
# 
# pligin.sbt is 

//Play2War plugin
resolvers += "Play2war plugins release" at "http://repository-play-war.forge.cloudbees.com/release/"
addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.2")

C:\activator-1.3.3\Tutorial\Play+Java+Spring\play-java-spring-master>activator run
[info] Loading project definition from C:\activator-1.3.3\Tutorial\Play+Java+Spring\play-java-spring-master\project
java.lang.AbstractMethodError
        at play.PlayInternalKeys$class.$init$(PlayInternalKeys.scala:20)
        at com.github.play2war.plugin.Play2WarPlugin$.<init>(Play2WarPlugin.scala:21)
        at com.github.play2war.plugin.Play2WarPlugin$.<clinit>(Play2WarPlugin.scala)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:14)
        at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:20)
        at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
        at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream$$anonfun$$plus$plus$1.apply(Stream.scala:330)
        at scala.collection.immutable.Stream$$anonfun$$plus$plus$1.apply(Stream.scala:330)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream.force(Stream.scala:249)
        at scala.collection.immutable.Stream.mkString(Stream.scala:702)
        at sbt.BuildUtil$.importNames(BuildUtil.scala:83)
        at sbt.BuildUtil$.importAll(BuildUtil.scala:88)
        at sbt.BuildUtil$.importAllRoot(BuildUtil.scala:89)
        at sbt.BuildUtil$.getImports(BuildUtil.scala:80)
        at sbt.DetectedPlugins.imports$lzycompute(BuildStructure.scala:125)
        at sbt.DetectedPlugins.imports(BuildStructure.scala:125)
        at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:710)
        at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:715)
        at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:714)
        at scala.Option.getOrElse(Option.scala:120)
        at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:714)
        at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:721)
        at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:721)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Load$.loadFiles$1(Load.scala:721)
        at sbt.Load$.discoverProjects(Load.scala:732)
        at sbt.Load$.discover$1(Load.scala:545)
        at sbt.Load$.loadTransitive(Load.scala:574)
        at sbt.Load$.loadProjects$1(Load.scala:442)
        at sbt.Load$.loadUnit(Load.scala:446)
        at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
        at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
        at sbt.BuildLoader.apply(BuildLoader.scala:140)
        at sbt.Load$.loadAll(Load.scala:334)
        at sbt.Load$.loadURI(Load.scala:289)
        at sbt.Load$.load(Load.scala:285)
        at sbt.Load$.load(Load.scala:276)
        at sbt.Load$.apply(Load.scala:130)
        at sbt.Load$.defaultLoad(Load.scala:36)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$.process(Command.scala:92)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:98)
        at sbt.MainLoop$.run(MainLoop.scala:91)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
        at sbt.MainLoop$.runLogged(MainLoop.scala:24)
        at sbt.StandardMain$.runManaged(Main.scala:53)
        at sbt.xMain.run(Main.scala:28)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:19)
        at xsbt.boot.Boot$.runImpl(Boot.scala:44)
        at xsbt.boot.Boot$.main(Boot.scala:20)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.AbstractMethodError
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? r

please sugget me

**Comment by yanns** [comment]
I do not think you are using Play 1.3.3 ;)
Please check your play version.
Please notice that you have to choose the play2war plugin version corresponding to your play version.

**Comment by dlecan** [comment]
Any news on this issue ?
Please reopen it if you have more information.
