### ISSUE TITLE
Not run Tomcat

### ISSUE THREAD

**Issue by nstreltsov** [play2war/play2-war-plugin#292]
Hi, All
All

I have play framework project https://github.com/nstreltsov/aplana-personal

I added play2war plugin. Generate war success After copy war to tomcat webapps folder and rename ROOT.war Startup Tomcat. Go to vy localhost http://localhost:8084/ open empty page.

i use play 2.4.0, play2war 1.4-beta1, tomcat 7

Please help me

Tomcat log have exception
catalina log

```
INFO: validateJarFile(C:\Program Files\Apache Software Foundation\Tomcat 7.0\webapps\GenerateReports\WEB-INF\lib\javaee-api-5.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
```

localhost.log

```
рту 09, 2015 12:57:16 AM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > contextInitialized
рту 09, 2015 12:57:17 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class play.core.server.servlet30.Play2Servlet
java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0 (unable to load class com.typesafe.config.ConfigException)
    at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2961)
    at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1210)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1690)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
    at play.api.ApplicationLoader$.createContext(ApplicationLoader.scala:91)
    at play.core.server.servlet.Play2WarServer$.<init>(Play2Server.scala:39)
    at play.core.server.servlet.Play2WarServer$.<clinit>(Play2Server.scala)
    at play.core.server.servlet.GenericPlay2Servlet.contextInitialized(GenericPlay2Servlet.scala:45)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by nstreltsov** [comment]
Found the solution. Use Tomcat 8

**Comment by dlecan** [comment]
Your real problem was:

```
java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0 (unable to load class com.typesafe.config.ConfigException)
```

which means you tried to execute Java code compiled with a higher version. Play 2.4 is compiled for Java 8 (bytecode 52.0) and you tried to run it with Java 7 or less.

**Comment by nstreltsov** [comment]
Thank you. It works

**Comment by kushNumberTheory** [comment]
Hi,
@nstreltsov 
I build restful api using play framework 2.4.2. Added Play2war plugins as suggested. We don't need web.xml as Routes file take care of POST and GET request.
My Routes file is:-
GET / controllers.Application.index
GET /assets/*file controllers.Assets.at(path="/public", file)
POST /createfile @controllers.scala.CaffeOnSpark.FileCreation

My Build.sbt include
name := "NT_CAFFE"
version := "1.0"
scalaVersion := "2.11.7"
lazy val NT_CAFFE = (project in file(".")).enablePlugins(PlayScala)
libraryDependencies ++= Seq( jdbc , cache , ws , specs2 % Test )
crossScalaVersions := Seq("2.10.4", "2.11.0", "2.11.1", "2.11.7")

My Plugins.sbt includes
logLevel := Level.Warn
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.2")
addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.4.0")

****My war file does not create class**.**   **I copy pasted it in the webapps folder of tomcat and deployed it. But it gives me Action Not found error. Please can you help me with this. What am i missing ?**
