### ISSUE TITLE
war file is not getting deployed when using Tomcat 8 embedded in Eclipse

### ISSUE THREAD

**Issue by prabharj** [play2war/play2-war-plugin#310]
The following error pops up:

Exception in thread "http-nio-8080-Acceptor-0" java.lang.ClassCircularityError: java/util/logging/LogRecord
    at org.slf4j.bridge.SLF4JBridgeHandler.getSLF4JLogger(SLF4JBridgeHandler.java:198)
    at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:293)
    at java.util.logging.Logger.log(Logger.java:738)
    at java.util.logging.Logger.doLog(Logger.java:765)
    at java.util.logging.Logger.logp(Logger.java:1041)
    at org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:182)
    at org.apache.juli.logging.DirectJDKLog.error(DirectJDKLog.java:148)
    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:741)
    at java.lang.Thread.run(Thread.java:745)

**Comment by prabharj** [comment]
Please note : Play version is 2.4.x , Eclipse Mars (4.5.2)
