### ISSUE TITLE
Something is wrong between AsyncListener and JBoss

### ISSUE THREAD

**Issue by dlecan** [play2war/play2-war-plugin#85]
`10:07:54,646 WARN  [org.jboss.as.ee] (MSC service thread 1-4) JBAS011006: Not installing optional component play.core.server.servlet30.AsyncListener due to exception: org.jboss.as.server.deployment.DeploymentUnitProcessingException: JBAS011054: Could not find default constructor for class play.core.server.servlet30.AsyncListener
    at org.jboss.as.ee.component.ComponentDescription$DefaultComponentConfigurator.configure(ComponentDescription.java:606) [jboss-as-ee-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
    at org.jboss.as.ee.component.deployers.EEModuleConfigurationProcessor.deploy(EEModuleConfigurationProcessor.java:83) [jboss-as-ee-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:116)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [classes.jar:1.6.0_33]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [classes.jar:1.6.0_33]
    at java.lang.Thread.run(Thread.java:680) [classes.jar:1.6.0_33]
`

**Comment by dlecan** [comment]
According to [this code](https://github.com/jbossas/jboss-as/blob/master/ee/src/main/java/org/jboss/as/ee/component/ComponentDescription.java#L605), Asynclistener in JBoss needs an empty args constructor.

**Comment by dlecan** [comment]
See https://issues.jboss.org/browse/AS7-5178
