### ISSUE TITLE
IBM WAS 7 throwing null pointer exception

### ISSUE THREAD

**Issue by drdamour** [play2war/play2-war-plugin#93]
after deploying the packed up default application to WAS 7 and attempting to access the root i'm getting a null pointer exception.  Here's the trace log output:

```
[9/26/12 17:31:08:898 EDT] 00000024 SystemOut     O 2012-09-26 17:31:08,897 - [TRACE] - from play in WebContainer : 1 
HTTP request received: com.ibm.ws.webcontainer.srt.SRTServletRequest@ebf0ebf

[9/26/12 17:31:08:900 EDT] 00000024 SystemOut     O 2012-09-26 17:31:08,900 - [TRACE] - from play in WebContainer : 1 
HTTP request content: GET /
URI: /
Method: GET
Path: /
Parameters: Map()
Headers: HOST: 192.168.122.167:9080
  ACCEPT-ENCODING: gzip,deflate,sdch
  ACCEPT-LANGUAGE: en-US,en;q=0.8
  ACCEPT-CHARSET: ISO-8859-1,utf-8;q=0.7,*;q=0.3
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1
Cookies: Map()

[9/26/12 17:31:08:901 EDT] 00000024 SystemOut     O 2012-09-26 17:31:08,901 - [ERROR] - from com.ibm.ws.webcontainer.servlet in WebContainer : 1 
SRVE0068E: Uncaught exception created in one of the service methods of the servlet play in application firstapp-1_0-SNAPSHOT_war. Exception created : java.lang.NullPointerException
    at play.core.server.servlet.Play2Servlet.service(Play2CommonServlet.scala:269)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:831)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1657)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:939)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:502)
    at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:179)
    at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:3933)
    at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:276)
    at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:931)
    at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1583)
    at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:186)
    at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:452)
    at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:511)
    at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:305)
    at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:276)
    at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
    at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
    at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:165)
    at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
    at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
    at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
    at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
    at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
    at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
    at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1604)
```

Not sure what i can do to help here, i'm willing to try anything.  I also get an error on startup:

```
[9/27/12 11:50:25:172 EDT] 0000000b ApplicationMg A   WSVR0200I: Starting application: firstapp-1_0-SNAPSHOT_war
[9/27/12 11:50:25:174 EDT] 0000000b ApplicationMg A   WSVR0204I: Application: firstapp-1_0-SNAPSHOT_war  Application build level: Unknown
[9/27/12 11:50:25:192 EDT] 0000000a ApplicationMg A   WSVR0200I: Starting application: jrules-res-htds-WAS7
[9/27/12 11:50:25:194 EDT] 0000000a ApplicationMg A   WSVR0203I: Application: jrules-res-htds-WAS7  Application build level: 7.1.1.0.9
[9/27/12 11:50:25:305 EDT] 0000000c ApplicationMg A   WSVR0200I: Starting application: CaseWidgets_ICM5100WINSQLNode01_server1
[9/27/12 11:50:25:328 EDT] 0000000c ApplicationMg A   WSVR0204I: Application: CaseWidgets_ICM5100WINSQLNode01_server1  Application build level: Unknown
[9/27/12 11:50:25:367 EDT] 0000000b webapp        I com.ibm.ws.webcontainer.webapp.WebGroupImpl WebGroup SRVE0169I: Loading Web Module: Play! firstapp.
[9/27/12 11:50:25:477 EDT] 0000000b WASSessionCor I SessionContextRegistry getSessionContext SESN0176I: Will create a new session context for application key default_host/
[9/27/12 11:50:25:559 EDT] 0000000b webapp        I com.ibm.ws.webcontainer.webapp.WebApp log SRVE0292I: Servlet Message - [firstapp-1_0-SNAPSHOT_war#firstapp-1.0-SNAPSHOT.war]:.PlayServletWrapper > contextInitialized
[9/27/12 11:50:26:771 EDT] 0000000b SystemOut     O 2012-09-27 11:50:26,766 - [DEBUG] - from play in server.startup : 1 
Plugin [play.api.db.BoneCPPlugin] is disabled

[9/27/12 11:50:26:784 EDT] 0000000b SystemOut     O 2012-09-27 11:50:26,781 - [DEBUG] - from play in server.startup : 1 
Plugin [play.api.db.evolutions.EvolutionsPlugin] is disabled

[9/27/12 11:50:27:052 EDT] 0000000b SystemOut     O 2012-09-27 11:50:27,052 - [ERROR] - from com.ibm.ws.webcontainer.webapp in server.startup : 1 
SRVE0283E: Exception caught while initializing context: {0}
play.api.i18n.Messages$MessagesParser$$anon$1: Configuration error [`=' expected but `
' found]
    at play.api.i18n.Messages$MessagesParser.parse(Messages.scala:181) ~[play.play_2.9.1-2.0.3.jar:2.0.3]
    at play.api.i18n.MessagesPlugin$$anonfun$play$api$i18n$MessagesPlugin$$loadMessages$1.apply(Messages.scala:231) ~[play.play_2.9.1-2.0.3.jar:2.0.3]
    at play.api.i18n.MessagesPlugin$$anonfun$play$api$i18n$MessagesPlugin$$loadMessages$1.apply(Messages.scala:230) ~[play.play_2.9.1-2.0.3.jar:2.0.3]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194) ~[org.scala-lang.scala-library-2.9.1.jar:na]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194) ~[org.scala-lang.scala-library-2.9.1.jar:na]
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59) ~[org.scala-lang.scala-library-2.9.1.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:45) ~[org.scala-lang.scala-library-2.9.1.jar:na]
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:194) ~[org.scala-lang.scala-library-2.9.1.jar:na]
    at scala.collection.immutable.List.map(List.scala:45) ~[org.scala-lang.scala-library-2.9.1.jar:na]
    at play.api.i18n.MessagesPlugin.play$api$i18n$MessagesPlugin$$loadMessages(Messages.scala:230) ~[play.play_2.9.1-2.0.3.jar:2.0.3]
    at play.api.i18n.MessagesPlugin.messages(Messages.scala:241) ~[play.play_2.9.1-2.0.3.jar:2.0.3]
    at play.api.i18n.MessagesPlugin.onStart(Messages.scala:254) ~[play.play_2.9.1-2.0.3.jar:2.0.3]
    at play.api.Play$$anonfun$start$1.apply(Play.scala:60) ~[play.play_2.9.1-2.0.3.jar:2.0.3]
    at play.api.Play$$anonfun$start$1.apply(Play.scala:60) ~[play.play_2.9.1-2.0.3.jar:2.0.3]
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59) ~[org.scala-lang.scala-library-2.9.1.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:45) ~[org.scala-lang.scala-library-2.9.1.jar:na]
    at play.api.Play$.start(Play.scala:60) ~[play.play_2.9.1-2.0.3.jar:2.0.3]
    at play.core.server.servlet.WarApplication.<init>(Play2Server.scala:49) ~[com.github.play2war.play2-war-core-common_2.9.1-0.7.4.jar:0.7.4]
    at play.core.server.servlet.Play2Servlet.contextInitialized(Play2CommonServlet.scala:364) ~[com.github.play2war.play2-war-core-common_2.9.1-0.7.4.jar:0.7.4]
    at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:1707) [com.ibm.ws.webcontainer.jar:na]
    at com.ibm.ws.webcontainer.webapp.WebApp.commonInitializationFinish(WebApp.java:380) [com.ibm.ws.webcontainer.jar:na]
    at com.ibm.ws.webcontainer.webapp.WebAppImpl.initialize(WebAppImpl.java:299) [com.ibm.ws.webcontainer.jar:na]
    at com.ibm.ws.webcontainer.webapp.WebGroupImpl.addWebApplication(WebGroupImpl.java:100) [com.ibm.ws.webcontainer.jar:na]
    at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:166) [com.ibm.ws.webcontainer.jar:na]
    at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:731) [com.ibm.ws.webcontainer.jar:na]
    at com.ibm.ws.webcontainer.WSWebContainer.addWebApplication(WSWebContainer.java:616) [com.ibm.ws.webcontainer.jar:na]
    at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:376) [com.ibm.ws.webcontainer.jar:na]
    at com.ibm.ws.webcontainer.component.WebContainerImpl.start(WebContainerImpl.java:668) [com.ibm.ws.webcontainer.jar:na]
    at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:1123) [com.ibm.ws.runtime.jar:na]
    at com.ibm.ws.runtime.component.DeployedApplicationImpl.fireDeployedObjectStart(DeployedApplicationImpl.java:1319) [com.ibm.ws.runtime.jar:na]
    at com.ibm.ws.runtime.component.DeployedModuleImpl.start(DeployedModuleImpl.java:610) [com.ibm.ws.runtime.jar:na]
    at com.ibm.ws.runtime.component.DeployedApplicationImpl.start(DeployedApplicationImpl.java:944) [com.ibm.ws.runtime.jar:na]
    at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:726) [com.ibm.ws.runtime.jar:na]
    at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:2048) [com.ibm.ws.runtime.jar:na]
    at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:441) [com.ibm.ws.runtime.jar:na]
    at com.ibm.ws.runtime.component.CompositionUnitImpl.start(CompositionUnitImpl.java:123) [com.ibm.ws.runtime.jar:na]
    at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:384) [com.ibm.ws.runtime.jar:na]
    at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.access$300(CompositionUnitMgrImpl.java:112) [com.ibm.ws.runtime.jar:na]
    at com.ibm.ws.runtime.component.CompositionUnitMgrImpl$CUInitializer.run(CompositionUnitMgrImpl.java:951) [com.ibm.ws.runtime.jar:na]
    at com.ibm.wsspi.runtime.component.WsComponentImpl$_AsynchInitializer.run(WsComponentImpl.java:349) [com.ibm.ws.runtime.jar:na]
    at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1604) [com.ibm.ws.runtime.jar:na]
```

but i'm thinking that's not too relevant.  I'm using play2-war-plugin 0.7.4

**Comment by dlecan** [comment]
Thank you for trying on WAS !

> Not sure what i can do to help here, i'm willing to try anything. I also get an error on startup:

Copy/paste error ? This is not a starting stacktrace.

BTW, NPE here (Play2Servlet.service(Play2CommonServlet.scala:269)) indicates that something was wrong during Play2War initialisation.(through a servlet listener).

But if something was wrong during initialisation (exception ?), why the application has been deployed ?

So I need starting logs, before any HTTP requests.
Thanks

**Comment by drdamour** [comment]
quite right on the copy paste error! i have updated the issue with the trace log from the relevant startup.  how does github not have attachments for issues!?!?

**Comment by dlecan** [comment]
```
[9/27/12 11:50:27:052 EDT] 0000000b SystemOut     O 2012-09-27 11:50:27,052 - [ERROR] - from com.ibm.ws.webcontainer.webapp in server.startup : 1 
SRVE0283E: Exception caught while initializing context: {0}
play.api.i18n.Messages$MessagesParser$$anon$1: Configuration error [`=' expected but `
' found]
    at play.api.i18n.Messages$MessagesParser.parse(Messages.scala:181) ~[play.play_2.9.1-2.0.3.jar:2.0.3]
```

Hum, you have something wrong with your configuration or translation files?

**Comment by drdamour** [comment]
i don't think so, i don't get the error in play run.  And this is literally the default application made from "play new firstapp"
This is my application.conf:

```
# This is the main configuration file for the application.
# ~~~~~

# Secret key
# ~~~~~
# The secret key is used to secure cryptographics functions.
# If you deploy your application to several instances be sure to use the same key!
application.secret="@BZMW_5VMdudpp/Fo;M;d0HCRwq?F5U^fP2;/Z4hV`9MwS665n`Mr@E0wKGPsbVI"

# The application languages
# ~~~~~
application.langs="en"

# Global object class
# ~~~~~
# Define the Global object class for this application.
# Default to Global in the root package.
# global=Global

# Database configuration
# ~~~~~ 
# You can declare as many datasources as you want.
# By convention, the default datasource is named `default`
#
# db.default.driver=org.h2.Driver
# db.default.url="jdbc:h2:mem:play"
# db.default.user=sa
# db.default.password=
#
# You can expose this datasource via JNDI if needed (Useful for JPA)
# db.default.jndiName=DefaultDS

# Evolutions
# ~~~~~
# You can disable evolutions if needed
# evolutionplugin=disabled

# Ebean configuration
# ~~~~~
# You can declare as many Ebean servers as you want.
# By convention, the default server is named `default`
#
# ebean.default="models.*"

# Logger
# ~~~~~
# You can also configure logback (http://logback.qos.ch/), by providing a logger.xml file in the conf directory .

# Root logger:
logger.root=TRACE

# Logger used by the framework:
logger.play=TRACE

# Logger provided to your application:
logger.application=TRACE
```

this is my routes:

```
# Routes
# This file defines all application routes (Higher priority routes first)
# ~~~~

# Home page
GET     /                           controllers.Application.index()

# Map static resources from the /public folder to the /assets URL path
GET     /assets/*file               controllers.Assets.at(path="/public", file)
```

my build file:

```
import sbt._
import Keys._
import PlayProject._
import com.github.play2war.plugin._

object ApplicationBuild extends Build {

    val appName         = "firstapp"
    val appVersion      = "1.0-SNAPSHOT"

    val appDependencies = Seq(
      // Add your project dependencies here,
    )

    val projectSettings = Play2WarPlugin.play2WarSettings ++ Seq(
        // Your settings
        Play2WarKeys.servletVersion := "2.5"
    )

    val main = PlayProject(appName, appVersion, appDependencies, mainLang = JAVA).settings(
      // Add your own project settings here 
      projectSettings: _*
    )


}
```

so i think everything is good...

looking at source it looks like the error is cause the server is null, there doesn't seem to be a lot of trace debugging about what configures that, is there a special branch i should try or a config setting missing?

**Comment by dlecan** [comment]
> looking at source it looks like the error is cause the server is null, there doesn't seem to be a lot of trace debugging about what configures that, is there a special branch i should try or a config setting missing?

Yes, server is null because initialisation failed.

Initialisation failed because of :

```
[9/27/12 11:50:27:052 EDT] 0000000b SystemOut     O 2012-09-27 11:50:27,052 - [ERROR] - from com.ibm.ws.webcontainer.webapp in server.startup : 1 
SRVE0283E: Exception caught while initializing context: {0}
play.api.i18n.Messages$MessagesParser$$anon$1: Configuration error [`=' expected but `
' found]
    at play.api.i18n.Messages$MessagesParser.parse(Messages.scala:181) ~[play.play_2.9.1-2.0.3.jar:2.0.3]
```

Very strange : despite this exception, webapp is deployed.

Play2War is a thin servlet wrapper around Play2 server during initialisation, and so you rely on Play logs.
And there is very, very few logs in Play code.
You have already enabled full traces with :

```
logger.root=TRACE
logger.play=TRACE
logger.application=TRACE
```

Exception is thrown here in Play code, I will investigate it:
https://github.com/playframework/Play20/blob/1f1013b492d1db23c6daddd81a53604ea96d52e6/framework/src/play/src/main/scala/play/api/i18n/Messages.scala#L181

**Comment by drdamour** [comment]
My app doesn't have a message file, could that be why?
if a webex/im/phone conversation would help i'm happy to participate as you need

**Comment by dlecan** [comment]
> My app doesn't have a message file, could that be why?

As `play run` works as expected, message is file not mandatory.
But it would be a good idea to test if adding a `conf/messages.en` file changes something. Does it ?

**Comment by dlecan** [comment]
@drdamour can you try to add a `conf/messages.en` file ?

**Comment by drdamour** [comment]
sorry to say that i had to move on to another framework (went with stripes, not nearly as good) and i no longer have legal access to WAS.

**Comment by dlecan** [comment]
ok, thanks

**Comment by cgalpin** [comment]
Damien, if you are still interested in seeing this run on Websphere (7)  I am ready to pick up where this left off.  I get the same error and I am pretty sure this is a classpath/class loader issue.  I know next to nothing about scala, but the file is loaded with app.classloader.getResources(file) and in our java code we have seen a difference between using  getClass().getResource(file).getFile() as opposed to getClass().getResourceAsStream(file) under WAS - the first doesn't fine the file properly but getResourceAsStream does.  

But to answer your last question, I included a conf/messages.en and the resulting war file has a messages file at the root, but no difference.  I assume the app classloader includes the root in it's classpath, but think the core issue is the file is not found.

Let me know if I should open a new issue.

Thanks,
charles

**Comment by cgalpin** [comment]
Sorry I didn't include this in my last message but I just noticed that if I do try to load the app, I see this error in the logs, which I think is telling.  It appears WAS is looking in WebSphere/AppServer/properties directory for the messages file, but this is actually a folder containing language directories like en which contain xml files with messages. 

```
Caused by: @6d5a50h2d: Configuration error in file:/C:/IBM/WebSphere/AppServer/properties/messages:1
    at play.api.i18n.Messages$MessagesParser.parse(Messages.scala:191)
    at play.api.i18n.MessagesPlugin$$anonfun$play$api$i18n$MessagesPlugin$$loadMessages$1.apply(Messages.scala:245)
    at play.api.i18n.MessagesPlugin$$anonfun$play$api$i18n$MessagesPlugin$$loadMessages$1.apply(Messages.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:309)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at play.api.i18n.MessagesPlugin.play$api$i18n$MessagesPlugin$$loadMessages(Messages.scala:244)
    at play.api.i18n.MessagesPlugin.messages$lzycompute(Messages.scala:255)
    at play.api.i18n.MessagesPlugin.messages(Messages.scala:251)
    at play.api.i18n.MessagesPlugin.onStart(Messages.scala:268)
    at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:63)
    at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:63)
    at scala.collection.immutable.List.foreach(List.scala:309)
    at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:63)
    at play.api.Play$$anonfun$start$1.apply(Play.scala:63)
    at play.api.Play$$anonfun$start$1.apply(Play.scala:63)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
    at play.api.Play$.start(Play.scala:62)
    at play.core.server.servlet.WarApplication.<init>(Play2Server.scala:90)
    at play.core.server.servlet.Play2WarServer$.<init>(Play2Server.scala:28)
    at play.core.server.servlet.Play2WarServer$.<clinit>(Play2Server.scala)
    at java.lang.J9VMInternals.initializeImpl(Native Method)
    at java.lang.J9VMInternals.initialize(J9VMInternals.java:200)
    at play.core.server.servlet.GenericPlay2Servlet.contextInitialized(Play2CommonServlet.scala:87)
```

**Comment by dlecan** [comment]
Thank you @cgalpin

Even if you and @drdamour have provided usefull stacktraces, I'm not able to fix this issue without more informations.

I well want to work on this, but @cgalpin you must be ready to deploy on your WAS7 test cases you can share.
@cgalpin, you're ready to do such thing, I'll open a new issue.

**Comment by cgalpin** [comment]
Hi Damien

Absolutely. Let me know what test cases you think would be useful. I am new to play! and scala so I am not sure what to try next.

Thanks,
charles

**Comment by dlecan** [comment]
@cgalpin see #128
